// @generated by protoc-gen-es v2.2.0 with parameter "target=dts,json_types=true,import_extension=js"
// @generated from file everstack/hosting/v1/hosting_service.proto (package everstack.hosting.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv1";
import type { ClaimSiteRequestSchema, ClaimSiteResponseSchema, DeleteSiteRequestSchema, DeleteSiteResponseSchema, FinalizeSiteRequestSchema, FinalizeSiteResponseSchema, GetSiteRequestSchema, GetSiteResponseSchema, HostingCapabilitiesRequestSchema, HostingCapabilitiesResponseSchema, HostingOverviewRequestSchema, HostingOverviewResponseSchema, ListAbuseReportsRequestSchema, ListAbuseReportsResponseSchema, ListOperatorSitesRequestSchema, ListOperatorSitesResponseSchema, ListSitesRequestSchema, ListSitesResponseSchema, PublishSiteRequestSchema, PublishSiteResponseSchema, ReportSiteRequestSchema, ReportSiteResponseSchema, RequestCodeRequestSchema, RequestCodeResponseSchema, RestoreSiteRequestSchema, RestoreSiteResponseSchema, ReviewAbuseReportRequestSchema, ReviewAbuseReportResponseSchema, TakedownSiteRequestSchema, TakedownSiteResponseSchema, UpdateSiteRequestSchema, UpdateSiteResponseSchema, VerifyCodeRequestSchema, VerifyCodeResponseSchema } from "./hosting_pb.js";

/**
 * Describes the file everstack/hosting/v1/hosting_service.proto.
 */
export declare const file_everstack_hosting_v1_hosting_service: GenFile;

/**
 * SitesService backs the evs.run instant static hosting product.
 * Public-route eligibility is enforced inside each handler. Anonymous
 * publishing is deployment-gated and disabled by default; abuse reports are
 * public and rate limited; tenant reads remain authenticated. Cross-tenant
 * inventory and moderation live exclusively on OperationsService.
 *
 * @generated from service everstack.hosting.v1.SitesService
 */
export declare const SitesService: GenService<{
  /**
   * @generated from rpc everstack.hosting.v1.SitesService.PublishSite
   */
  publishSite: {
    methodKind: "unary";
    input: typeof PublishSiteRequestSchema;
    output: typeof PublishSiteResponseSchema;
  },
  /**
   * @generated from rpc everstack.hosting.v1.SitesService.FinalizeSite
   */
  finalizeSite: {
    methodKind: "unary";
    input: typeof FinalizeSiteRequestSchema;
    output: typeof FinalizeSiteResponseSchema;
  },
  /**
   * @generated from rpc everstack.hosting.v1.SitesService.GetSite
   */
  getSite: {
    methodKind: "unary";
    input: typeof GetSiteRequestSchema;
    output: typeof GetSiteResponseSchema;
  },
  /**
   * @generated from rpc everstack.hosting.v1.SitesService.ListSites
   */
  listSites: {
    methodKind: "unary";
    input: typeof ListSitesRequestSchema;
    output: typeof ListSitesResponseSchema;
  },
  /**
   * @generated from rpc everstack.hosting.v1.SitesService.UpdateSite
   */
  updateSite: {
    methodKind: "unary";
    input: typeof UpdateSiteRequestSchema;
    output: typeof UpdateSiteResponseSchema;
  },
  /**
   * @generated from rpc everstack.hosting.v1.SitesService.DeleteSite
   */
  deleteSite: {
    methodKind: "unary";
    input: typeof DeleteSiteRequestSchema;
    output: typeof DeleteSiteResponseSchema;
  },
  /**
   * @generated from rpc everstack.hosting.v1.SitesService.ReportSite
   */
  reportSite: {
    methodKind: "unary";
    input: typeof ReportSiteRequestSchema;
    output: typeof ReportSiteResponseSchema;
  },
  /**
   * Retained as a customer-safe capability probe. Cross-tenant operator
   * authorization is intentionally always false on this service.
   *
   * @generated from rpc everstack.hosting.v1.SitesService.GetHostingCapabilities
   */
  getHostingCapabilities: {
    methodKind: "unary";
    input: typeof HostingCapabilitiesRequestSchema;
    output: typeof HostingCapabilitiesResponseSchema;
  },
  /**
   * Deprecated wire-compatibility stubs. Operator functionality moved to the
   * private OperationsService; these methods have no public HTTP bindings and
   * return UNIMPLEMENTED from customer gateways.
   *
   * @generated from rpc everstack.hosting.v1.SitesService.TakedownSite
   * @deprecated
   */
  takedownSite: {
    methodKind: "unary";
    input: typeof TakedownSiteRequestSchema;
    output: typeof TakedownSiteResponseSchema;
  },
  /**
   * @generated from rpc everstack.hosting.v1.SitesService.RestoreSite
   * @deprecated
   */
  restoreSite: {
    methodKind: "unary";
    input: typeof RestoreSiteRequestSchema;
    output: typeof RestoreSiteResponseSchema;
  },
  /**
   * @generated from rpc everstack.hosting.v1.SitesService.GetHostingOverview
   * @deprecated
   */
  getHostingOverview: {
    methodKind: "unary";
    input: typeof HostingOverviewRequestSchema;
    output: typeof HostingOverviewResponseSchema;
  },
  /**
   * @generated from rpc everstack.hosting.v1.SitesService.ListOperatorSites
   * @deprecated
   */
  listOperatorSites: {
    methodKind: "unary";
    input: typeof ListOperatorSitesRequestSchema;
    output: typeof ListOperatorSitesResponseSchema;
  },
  /**
   * @generated from rpc everstack.hosting.v1.SitesService.ListAbuseReports
   * @deprecated
   */
  listAbuseReports: {
    methodKind: "unary";
    input: typeof ListAbuseReportsRequestSchema;
    output: typeof ListAbuseReportsResponseSchema;
  },
  /**
   * @generated from rpc everstack.hosting.v1.SitesService.ReviewAbuseReport
   * @deprecated
   */
  reviewAbuseReport: {
    methodKind: "unary";
    input: typeof ReviewAbuseReportRequestSchema;
    output: typeof ReviewAbuseReportResponseSchema;
  },
  /**
   * @generated from rpc everstack.hosting.v1.SitesService.ClaimSite
   */
  claimSite: {
    methodKind: "unary";
    input: typeof ClaimSiteRequestSchema;
    output: typeof ClaimSiteResponseSchema;
  },
  /**
   * @generated from rpc everstack.hosting.v1.SitesService.RequestCode
   */
  requestCode: {
    methodKind: "unary";
    input: typeof RequestCodeRequestSchema;
    output: typeof RequestCodeResponseSchema;
  },
  /**
   * @generated from rpc everstack.hosting.v1.SitesService.VerifyCode
   */
  verifyCode: {
    methodKind: "unary";
    input: typeof VerifyCodeRequestSchema;
    output: typeof VerifyCodeResponseSchema;
  },
}>;

