// @generated by protoc-gen-es v2.2.0 with parameter "target=dts,json_types=true,import_extension=js"
// @generated from file everstack/controlplane/v1/controlplane.proto (package everstack.controlplane.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp, TimestampJson } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file everstack/controlplane/v1/controlplane.proto.
 */
export declare const file_everstack_controlplane_v1_controlplane: GenFile;

/**
 * InstanceResources describes the resource allocation and usage for an instance.
 *
 * @generated from message everstack.controlplane.v1.InstanceResources
 */
export declare type InstanceResources = Message<"everstack.controlplane.v1.InstanceResources"> & {
  /**
   * @generated from field: double cpu_limit = 1;
   */
  cpuLimit: number;

  /**
   * @generated from field: int64 memory_mb = 2;
   */
  memoryMb: bigint;

  /**
   * @generated from field: int64 disk_mb = 3;
   */
  diskMb: bigint;

  /**
   * @generated from field: double cpu_usage = 4;
   */
  cpuUsage: number;

  /**
   * @generated from field: int64 memory_usage_mb = 5;
   */
  memoryUsageMb: bigint;

  /**
   * @generated from field: int64 active_connections = 6;
   */
  activeConnections: bigint;
};

/**
 * InstanceResources describes the resource allocation and usage for an instance.
 *
 * @generated from message everstack.controlplane.v1.InstanceResources
 */
export declare type InstanceResourcesJson = {
  /**
   * @generated from field: double cpu_limit = 1;
   */
  cpuLimit?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * @generated from field: int64 memory_mb = 2;
   */
  memoryMb?: string;

  /**
   * @generated from field: int64 disk_mb = 3;
   */
  diskMb?: string;

  /**
   * @generated from field: double cpu_usage = 4;
   */
  cpuUsage?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * @generated from field: int64 memory_usage_mb = 5;
   */
  memoryUsageMb?: string;

  /**
   * @generated from field: int64 active_connections = 6;
   */
  activeConnections?: string;
};

/**
 * Describes the message everstack.controlplane.v1.InstanceResources.
 * Use `create(InstanceResourcesSchema)` to create a new message.
 */
export declare const InstanceResourcesSchema: GenMessage<InstanceResources, InstanceResourcesJson>;

/**
 * InstanceHealth describes the health status of an instance.
 *
 * @generated from message everstack.controlplane.v1.InstanceHealth
 */
export declare type InstanceHealth = Message<"everstack.controlplane.v1.InstanceHealth"> & {
  /**
   * @generated from field: bool healthy = 1;
   */
  healthy: boolean;

  /**
   * @generated from field: google.protobuf.Timestamp last_check = 2;
   */
  lastCheck?: Timestamp;

  /**
   * @generated from field: int32 consecutive_failures = 3;
   */
  consecutiveFailures: number;

  /**
   * @generated from field: string last_error = 4;
   */
  lastError: string;

  /**
   * @generated from field: int64 uptime_seconds = 5;
   */
  uptimeSeconds: bigint;
};

/**
 * InstanceHealth describes the health status of an instance.
 *
 * @generated from message everstack.controlplane.v1.InstanceHealth
 */
export declare type InstanceHealthJson = {
  /**
   * @generated from field: bool healthy = 1;
   */
  healthy?: boolean;

  /**
   * @generated from field: google.protobuf.Timestamp last_check = 2;
   */
  lastCheck?: TimestampJson;

  /**
   * @generated from field: int32 consecutive_failures = 3;
   */
  consecutiveFailures?: number;

  /**
   * @generated from field: string last_error = 4;
   */
  lastError?: string;

  /**
   * @generated from field: int64 uptime_seconds = 5;
   */
  uptimeSeconds?: string;
};

/**
 * Describes the message everstack.controlplane.v1.InstanceHealth.
 * Use `create(InstanceHealthSchema)` to create a new message.
 */
export declare const InstanceHealthSchema: GenMessage<InstanceHealth, InstanceHealthJson>;

/**
 * GatewayInstance represents a managed gateway instance.
 *
 * @generated from message everstack.controlplane.v1.GatewayInstance
 */
export declare type GatewayInstance = Message<"everstack.controlplane.v1.GatewayInstance"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string workspace_id = 2;
   */
  workspaceId: string;

  /**
   * @generated from field: string organization_id = 3;
   */
  organizationId: string;

  /**
   * @generated from field: string slug = 4;
   */
  slug: string;

  /**
   * @generated from field: string gateway_url = 5;
   */
  gatewayUrl: string;

  /**
   * @generated from field: string internal_url = 6;
   */
  internalUrl: string;

  /**
   * @generated from field: everstack.controlplane.v1.InstanceStatus status = 7;
   */
  status: InstanceStatus;

  /**
   * @generated from field: string version = 8;
   */
  version: string;

  /**
   * @generated from field: string environment = 9;
   */
  environment: string;

  /**
   * @generated from field: everstack.controlplane.v1.InstanceResources resources = 10;
   */
  resources?: InstanceResources;

  /**
   * @generated from field: everstack.controlplane.v1.InstanceHealth health = 11;
   */
  health?: InstanceHealth;

  /**
   * @generated from field: string container_id = 12;
   */
  containerId: string;

  /**
   * @generated from field: string m2m_instance_id = 13;
   */
  m2mInstanceId: string;

  /**
   * @generated from field: string backend_type = 14;
   */
  backendType: string;

  /**
   * @generated from field: string error_reason = 15;
   */
  errorReason: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 16;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 17;
   */
  updatedAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp stopped_at = 18;
   */
  stoppedAt?: Timestamp;

  /**
   * @generated from field: string schema_name = 19;
   */
  schemaName: string;

  /**
   * @generated from field: string custom_domain = 20;
   */
  customDomain: string;

  /**
   * "" | "pending_dns" | "verifying" | "active" | "failed"
   *
   * @generated from field: string custom_domain_status = 21;
   */
  customDomainStatus: string;

  /**
   * "eu", "americas", ...
   *
   * @generated from field: string region = 22;
   */
  region: string;
};

/**
 * GatewayInstance represents a managed gateway instance.
 *
 * @generated from message everstack.controlplane.v1.GatewayInstance
 */
export declare type GatewayInstanceJson = {
  /**
   * @generated from field: string id = 1;
   */
  id?: string;

  /**
   * @generated from field: string workspace_id = 2;
   */
  workspaceId?: string;

  /**
   * @generated from field: string organization_id = 3;
   */
  organizationId?: string;

  /**
   * @generated from field: string slug = 4;
   */
  slug?: string;

  /**
   * @generated from field: string gateway_url = 5;
   */
  gatewayUrl?: string;

  /**
   * @generated from field: string internal_url = 6;
   */
  internalUrl?: string;

  /**
   * @generated from field: everstack.controlplane.v1.InstanceStatus status = 7;
   */
  status?: InstanceStatusJson;

  /**
   * @generated from field: string version = 8;
   */
  version?: string;

  /**
   * @generated from field: string environment = 9;
   */
  environment?: string;

  /**
   * @generated from field: everstack.controlplane.v1.InstanceResources resources = 10;
   */
  resources?: InstanceResourcesJson;

  /**
   * @generated from field: everstack.controlplane.v1.InstanceHealth health = 11;
   */
  health?: InstanceHealthJson;

  /**
   * @generated from field: string container_id = 12;
   */
  containerId?: string;

  /**
   * @generated from field: string m2m_instance_id = 13;
   */
  m2mInstanceId?: string;

  /**
   * @generated from field: string backend_type = 14;
   */
  backendType?: string;

  /**
   * @generated from field: string error_reason = 15;
   */
  errorReason?: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 16;
   */
  createdAt?: TimestampJson;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 17;
   */
  updatedAt?: TimestampJson;

  /**
   * @generated from field: google.protobuf.Timestamp stopped_at = 18;
   */
  stoppedAt?: TimestampJson;

  /**
   * @generated from field: string schema_name = 19;
   */
  schemaName?: string;

  /**
   * @generated from field: string custom_domain = 20;
   */
  customDomain?: string;

  /**
   * "" | "pending_dns" | "verifying" | "active" | "failed"
   *
   * @generated from field: string custom_domain_status = 21;
   */
  customDomainStatus?: string;

  /**
   * "eu", "americas", ...
   *
   * @generated from field: string region = 22;
   */
  region?: string;
};

/**
 * Describes the message everstack.controlplane.v1.GatewayInstance.
 * Use `create(GatewayInstanceSchema)` to create a new message.
 */
export declare const GatewayInstanceSchema: GenMessage<GatewayInstance, GatewayInstanceJson>;

/**
 * @generated from message everstack.controlplane.v1.ProvisionInstanceRequest
 */
export declare type ProvisionInstanceRequest = Message<"everstack.controlplane.v1.ProvisionInstanceRequest"> & {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId: string;

  /**
   * @generated from field: string organization_id = 2;
   */
  organizationId: string;

  /**
   * @generated from field: string slug = 3;
   */
  slug: string;

  /**
   * @generated from field: string environment = 4;
   */
  environment: string;

  /**
   * @generated from field: string version = 5;
   */
  version: string;

  /**
   * @generated from field: double cpu_limit = 6;
   */
  cpuLimit: number;

  /**
   * @generated from field: int64 memory_mb = 7;
   */
  memoryMb: bigint;

  /**
   * @generated from field: string org_slug = 8;
   */
  orgSlug: string;

  /**
   * Region to provision into. Empty = controlplane default. Rejected
   * with InvalidArgument if not in the controlplane's allow-list.
   *
   * @generated from field: string region = 9;
   */
  region: string;
};

/**
 * @generated from message everstack.controlplane.v1.ProvisionInstanceRequest
 */
export declare type ProvisionInstanceRequestJson = {
  /**
   * @generated from field: string workspace_id = 1;
   */
  workspaceId?: string;

  /**
   * @generated from field: string organization_id = 2;
   */
  organizationId?: string;

  /**
   * @generated from field: string slug = 3;
   */
  slug?: string;

  /**
   * @generated from field: string environment = 4;
   */
  environment?: string;

  /**
   * @generated from field: string version = 5;
   */
  version?: string;

  /**
   * @generated from field: double cpu_limit = 6;
   */
  cpuLimit?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * @generated from field: int64 memory_mb = 7;
   */
  memoryMb?: string;

  /**
   * @generated from field: string org_slug = 8;
   */
  orgSlug?: string;

  /**
   * Region to provision into. Empty = controlplane default. Rejected
   * with InvalidArgument if not in the controlplane's allow-list.
   *
   * @generated from field: string region = 9;
   */
  region?: string;
};

/**
 * Describes the message everstack.controlplane.v1.ProvisionInstanceRequest.
 * Use `create(ProvisionInstanceRequestSchema)` to create a new message.
 */
export declare const ProvisionInstanceRequestSchema: GenMessage<ProvisionInstanceRequest, ProvisionInstanceRequestJson>;

/**
 * @generated from message everstack.controlplane.v1.ListRegionsRequest
 */
export declare type ListRegionsRequest = Message<"everstack.controlplane.v1.ListRegionsRequest"> & {
};

/**
 * @generated from message everstack.controlplane.v1.ListRegionsRequest
 */
export declare type ListRegionsRequestJson = {
};

/**
 * Describes the message everstack.controlplane.v1.ListRegionsRequest.
 * Use `create(ListRegionsRequestSchema)` to create a new message.
 */
export declare const ListRegionsRequestSchema: GenMessage<ListRegionsRequest, ListRegionsRequestJson>;

/**
 * @generated from message everstack.controlplane.v1.Region
 */
export declare type Region = Message<"everstack.controlplane.v1.Region"> & {
  /**
   * city-level slug ("eu-fra-1", "us-pdx-1")
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * "Frankfurt (eu-fra-1)", "Oregon (us-pdx-1)"
   *
   * @generated from field: string display_name = 2;
   */
  displayName: string;

  /**
   * "🇩🇪", "🇺🇸"
   *
   * @generated from field: string flag_emoji = 3;
   */
  flagEmoji: string;

  /**
   * false for greyed-out options
   *
   * @generated from field: bool available = 4;
   */
  available: boolean;
};

/**
 * @generated from message everstack.controlplane.v1.Region
 */
export declare type RegionJson = {
  /**
   * city-level slug ("eu-fra-1", "us-pdx-1")
   *
   * @generated from field: string id = 1;
   */
  id?: string;

  /**
   * "Frankfurt (eu-fra-1)", "Oregon (us-pdx-1)"
   *
   * @generated from field: string display_name = 2;
   */
  displayName?: string;

  /**
   * "🇩🇪", "🇺🇸"
   *
   * @generated from field: string flag_emoji = 3;
   */
  flagEmoji?: string;

  /**
   * false for greyed-out options
   *
   * @generated from field: bool available = 4;
   */
  available?: boolean;
};

/**
 * Describes the message everstack.controlplane.v1.Region.
 * Use `create(RegionSchema)` to create a new message.
 */
export declare const RegionSchema: GenMessage<Region, RegionJson>;

/**
 * @generated from message everstack.controlplane.v1.ListRegionsResponse
 */
export declare type ListRegionsResponse = Message<"everstack.controlplane.v1.ListRegionsResponse"> & {
  /**
   * @generated from field: repeated everstack.controlplane.v1.Region regions = 1;
   */
  regions: Region[];

  /**
   * @generated from field: string default_region = 2;
   */
  defaultRegion: string;
};

/**
 * @generated from message everstack.controlplane.v1.ListRegionsResponse
 */
export declare type ListRegionsResponseJson = {
  /**
   * @generated from field: repeated everstack.controlplane.v1.Region regions = 1;
   */
  regions?: RegionJson[];

  /**
   * @generated from field: string default_region = 2;
   */
  defaultRegion?: string;
};

/**
 * Describes the message everstack.controlplane.v1.ListRegionsResponse.
 * Use `create(ListRegionsResponseSchema)` to create a new message.
 */
export declare const ListRegionsResponseSchema: GenMessage<ListRegionsResponse, ListRegionsResponseJson>;

/**
 * @generated from message everstack.controlplane.v1.ProvisionInstanceResponse
 */
export declare type ProvisionInstanceResponse = Message<"everstack.controlplane.v1.ProvisionInstanceResponse"> & {
  /**
   * @generated from field: everstack.controlplane.v1.GatewayInstance instance = 1;
   */
  instance?: GatewayInstance;
};

/**
 * @generated from message everstack.controlplane.v1.ProvisionInstanceResponse
 */
export declare type ProvisionInstanceResponseJson = {
  /**
   * @generated from field: everstack.controlplane.v1.GatewayInstance instance = 1;
   */
  instance?: GatewayInstanceJson;
};

/**
 * Describes the message everstack.controlplane.v1.ProvisionInstanceResponse.
 * Use `create(ProvisionInstanceResponseSchema)` to create a new message.
 */
export declare const ProvisionInstanceResponseSchema: GenMessage<ProvisionInstanceResponse, ProvisionInstanceResponseJson>;

/**
 * @generated from message everstack.controlplane.v1.GetInstanceRequest
 */
export declare type GetInstanceRequest = Message<"everstack.controlplane.v1.GetInstanceRequest"> & {
  /**
   * @generated from oneof everstack.controlplane.v1.GetInstanceRequest.identifier
   */
  identifier: {
    /**
     * @generated from field: string instance_id = 1;
     */
    value: string;
    case: "instanceId";
  } | {
    /**
     * @generated from field: string workspace_id = 2;
     */
    value: string;
    case: "workspaceId";
  } | { case: undefined; value?: undefined };
};

/**
 * @generated from message everstack.controlplane.v1.GetInstanceRequest
 */
export declare type GetInstanceRequestJson = {
  /**
   * @generated from field: string instance_id = 1;
   */
  instanceId?: string;

  /**
   * @generated from field: string workspace_id = 2;
   */
  workspaceId?: string;
};

/**
 * Describes the message everstack.controlplane.v1.GetInstanceRequest.
 * Use `create(GetInstanceRequestSchema)` to create a new message.
 */
export declare const GetInstanceRequestSchema: GenMessage<GetInstanceRequest, GetInstanceRequestJson>;

/**
 * @generated from message everstack.controlplane.v1.GetInstanceResponse
 */
export declare type GetInstanceResponse = Message<"everstack.controlplane.v1.GetInstanceResponse"> & {
  /**
   * @generated from field: everstack.controlplane.v1.GatewayInstance instance = 1;
   */
  instance?: GatewayInstance;
};

/**
 * @generated from message everstack.controlplane.v1.GetInstanceResponse
 */
export declare type GetInstanceResponseJson = {
  /**
   * @generated from field: everstack.controlplane.v1.GatewayInstance instance = 1;
   */
  instance?: GatewayInstanceJson;
};

/**
 * Describes the message everstack.controlplane.v1.GetInstanceResponse.
 * Use `create(GetInstanceResponseSchema)` to create a new message.
 */
export declare const GetInstanceResponseSchema: GenMessage<GetInstanceResponse, GetInstanceResponseJson>;

/**
 * @generated from message everstack.controlplane.v1.ListInstancesRequest
 */
export declare type ListInstancesRequest = Message<"everstack.controlplane.v1.ListInstancesRequest"> & {
  /**
   * @generated from field: string organization_id = 1;
   */
  organizationId: string;
};

/**
 * @generated from message everstack.controlplane.v1.ListInstancesRequest
 */
export declare type ListInstancesRequestJson = {
  /**
   * @generated from field: string organization_id = 1;
   */
  organizationId?: string;
};

/**
 * Describes the message everstack.controlplane.v1.ListInstancesRequest.
 * Use `create(ListInstancesRequestSchema)` to create a new message.
 */
export declare const ListInstancesRequestSchema: GenMessage<ListInstancesRequest, ListInstancesRequestJson>;

/**
 * @generated from message everstack.controlplane.v1.ListInstancesResponse
 */
export declare type ListInstancesResponse = Message<"everstack.controlplane.v1.ListInstancesResponse"> & {
  /**
   * @generated from field: repeated everstack.controlplane.v1.GatewayInstance instances = 1;
   */
  instances: GatewayInstance[];

  /**
   * Number of active instances
   *
   * @generated from field: int32 instance_count = 2;
   */
  instanceCount: number;

  /**
   * Max allowed instances for the org's plan (0 = unlimited)
   *
   * @generated from field: int32 instance_limit = 3;
   */
  instanceLimit: number;
};

/**
 * @generated from message everstack.controlplane.v1.ListInstancesResponse
 */
export declare type ListInstancesResponseJson = {
  /**
   * @generated from field: repeated everstack.controlplane.v1.GatewayInstance instances = 1;
   */
  instances?: GatewayInstanceJson[];

  /**
   * Number of active instances
   *
   * @generated from field: int32 instance_count = 2;
   */
  instanceCount?: number;

  /**
   * Max allowed instances for the org's plan (0 = unlimited)
   *
   * @generated from field: int32 instance_limit = 3;
   */
  instanceLimit?: number;
};

/**
 * Describes the message everstack.controlplane.v1.ListInstancesResponse.
 * Use `create(ListInstancesResponseSchema)` to create a new message.
 */
export declare const ListInstancesResponseSchema: GenMessage<ListInstancesResponse, ListInstancesResponseJson>;

/**
 * @generated from message everstack.controlplane.v1.StartInstanceRequest
 */
export declare type StartInstanceRequest = Message<"everstack.controlplane.v1.StartInstanceRequest"> & {
  /**
   * @generated from field: string instance_id = 1;
   */
  instanceId: string;
};

/**
 * @generated from message everstack.controlplane.v1.StartInstanceRequest
 */
export declare type StartInstanceRequestJson = {
  /**
   * @generated from field: string instance_id = 1;
   */
  instanceId?: string;
};

/**
 * Describes the message everstack.controlplane.v1.StartInstanceRequest.
 * Use `create(StartInstanceRequestSchema)` to create a new message.
 */
export declare const StartInstanceRequestSchema: GenMessage<StartInstanceRequest, StartInstanceRequestJson>;

/**
 * @generated from message everstack.controlplane.v1.StartInstanceResponse
 */
export declare type StartInstanceResponse = Message<"everstack.controlplane.v1.StartInstanceResponse"> & {
  /**
   * @generated from field: everstack.controlplane.v1.GatewayInstance instance = 1;
   */
  instance?: GatewayInstance;
};

/**
 * @generated from message everstack.controlplane.v1.StartInstanceResponse
 */
export declare type StartInstanceResponseJson = {
  /**
   * @generated from field: everstack.controlplane.v1.GatewayInstance instance = 1;
   */
  instance?: GatewayInstanceJson;
};

/**
 * Describes the message everstack.controlplane.v1.StartInstanceResponse.
 * Use `create(StartInstanceResponseSchema)` to create a new message.
 */
export declare const StartInstanceResponseSchema: GenMessage<StartInstanceResponse, StartInstanceResponseJson>;

/**
 * @generated from message everstack.controlplane.v1.StopInstanceRequest
 */
export declare type StopInstanceRequest = Message<"everstack.controlplane.v1.StopInstanceRequest"> & {
  /**
   * @generated from field: string instance_id = 1;
   */
  instanceId: string;

  /**
   * @generated from field: bool graceful = 2;
   */
  graceful: boolean;
};

/**
 * @generated from message everstack.controlplane.v1.StopInstanceRequest
 */
export declare type StopInstanceRequestJson = {
  /**
   * @generated from field: string instance_id = 1;
   */
  instanceId?: string;

  /**
   * @generated from field: bool graceful = 2;
   */
  graceful?: boolean;
};

/**
 * Describes the message everstack.controlplane.v1.StopInstanceRequest.
 * Use `create(StopInstanceRequestSchema)` to create a new message.
 */
export declare const StopInstanceRequestSchema: GenMessage<StopInstanceRequest, StopInstanceRequestJson>;

/**
 * @generated from message everstack.controlplane.v1.StopInstanceResponse
 */
export declare type StopInstanceResponse = Message<"everstack.controlplane.v1.StopInstanceResponse"> & {
  /**
   * @generated from field: everstack.controlplane.v1.GatewayInstance instance = 1;
   */
  instance?: GatewayInstance;
};

/**
 * @generated from message everstack.controlplane.v1.StopInstanceResponse
 */
export declare type StopInstanceResponseJson = {
  /**
   * @generated from field: everstack.controlplane.v1.GatewayInstance instance = 1;
   */
  instance?: GatewayInstanceJson;
};

/**
 * Describes the message everstack.controlplane.v1.StopInstanceResponse.
 * Use `create(StopInstanceResponseSchema)` to create a new message.
 */
export declare const StopInstanceResponseSchema: GenMessage<StopInstanceResponse, StopInstanceResponseJson>;

/**
 * @generated from message everstack.controlplane.v1.RestartInstanceRequest
 */
export declare type RestartInstanceRequest = Message<"everstack.controlplane.v1.RestartInstanceRequest"> & {
  /**
   * @generated from field: string instance_id = 1;
   */
  instanceId: string;
};

/**
 * @generated from message everstack.controlplane.v1.RestartInstanceRequest
 */
export declare type RestartInstanceRequestJson = {
  /**
   * @generated from field: string instance_id = 1;
   */
  instanceId?: string;
};

/**
 * Describes the message everstack.controlplane.v1.RestartInstanceRequest.
 * Use `create(RestartInstanceRequestSchema)` to create a new message.
 */
export declare const RestartInstanceRequestSchema: GenMessage<RestartInstanceRequest, RestartInstanceRequestJson>;

/**
 * @generated from message everstack.controlplane.v1.RestartInstanceResponse
 */
export declare type RestartInstanceResponse = Message<"everstack.controlplane.v1.RestartInstanceResponse"> & {
  /**
   * @generated from field: everstack.controlplane.v1.GatewayInstance instance = 1;
   */
  instance?: GatewayInstance;
};

/**
 * @generated from message everstack.controlplane.v1.RestartInstanceResponse
 */
export declare type RestartInstanceResponseJson = {
  /**
   * @generated from field: everstack.controlplane.v1.GatewayInstance instance = 1;
   */
  instance?: GatewayInstanceJson;
};

/**
 * Describes the message everstack.controlplane.v1.RestartInstanceResponse.
 * Use `create(RestartInstanceResponseSchema)` to create a new message.
 */
export declare const RestartInstanceResponseSchema: GenMessage<RestartInstanceResponse, RestartInstanceResponseJson>;

/**
 * @generated from message everstack.controlplane.v1.DeleteInstanceRequest
 */
export declare type DeleteInstanceRequest = Message<"everstack.controlplane.v1.DeleteInstanceRequest"> & {
  /**
   * @generated from field: string instance_id = 1;
   */
  instanceId: string;
};

/**
 * @generated from message everstack.controlplane.v1.DeleteInstanceRequest
 */
export declare type DeleteInstanceRequestJson = {
  /**
   * @generated from field: string instance_id = 1;
   */
  instanceId?: string;
};

/**
 * Describes the message everstack.controlplane.v1.DeleteInstanceRequest.
 * Use `create(DeleteInstanceRequestSchema)` to create a new message.
 */
export declare const DeleteInstanceRequestSchema: GenMessage<DeleteInstanceRequest, DeleteInstanceRequestJson>;

/**
 * @generated from message everstack.controlplane.v1.DeleteInstanceResponse
 */
export declare type DeleteInstanceResponse = Message<"everstack.controlplane.v1.DeleteInstanceResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * @generated from message everstack.controlplane.v1.DeleteInstanceResponse
 */
export declare type DeleteInstanceResponseJson = {
  /**
   * @generated from field: bool success = 1;
   */
  success?: boolean;
};

/**
 * Describes the message everstack.controlplane.v1.DeleteInstanceResponse.
 * Use `create(DeleteInstanceResponseSchema)` to create a new message.
 */
export declare const DeleteInstanceResponseSchema: GenMessage<DeleteInstanceResponse, DeleteInstanceResponseJson>;

/**
 * @generated from message everstack.controlplane.v1.GetInstanceLogsRequest
 */
export declare type GetInstanceLogsRequest = Message<"everstack.controlplane.v1.GetInstanceLogsRequest"> & {
  /**
   * @generated from field: string instance_id = 1;
   */
  instanceId: string;

  /**
   * @generated from field: int32 tail = 2;
   */
  tail: number;

  /**
   * @generated from field: bool follow = 3;
   */
  follow: boolean;
};

/**
 * @generated from message everstack.controlplane.v1.GetInstanceLogsRequest
 */
export declare type GetInstanceLogsRequestJson = {
  /**
   * @generated from field: string instance_id = 1;
   */
  instanceId?: string;

  /**
   * @generated from field: int32 tail = 2;
   */
  tail?: number;

  /**
   * @generated from field: bool follow = 3;
   */
  follow?: boolean;
};

/**
 * Describes the message everstack.controlplane.v1.GetInstanceLogsRequest.
 * Use `create(GetInstanceLogsRequestSchema)` to create a new message.
 */
export declare const GetInstanceLogsRequestSchema: GenMessage<GetInstanceLogsRequest, GetInstanceLogsRequestJson>;

/**
 * @generated from message everstack.controlplane.v1.GetInstanceLogsResponse
 */
export declare type GetInstanceLogsResponse = Message<"everstack.controlplane.v1.GetInstanceLogsResponse"> & {
  /**
   * @generated from field: repeated string lines = 1;
   */
  lines: string[];
};

/**
 * @generated from message everstack.controlplane.v1.GetInstanceLogsResponse
 */
export declare type GetInstanceLogsResponseJson = {
  /**
   * @generated from field: repeated string lines = 1;
   */
  lines?: string[];
};

/**
 * Describes the message everstack.controlplane.v1.GetInstanceLogsResponse.
 * Use `create(GetInstanceLogsResponseSchema)` to create a new message.
 */
export declare const GetInstanceLogsResponseSchema: GenMessage<GetInstanceLogsResponse, GetInstanceLogsResponseJson>;

/**
 * @generated from message everstack.controlplane.v1.PushConfigRequest
 */
export declare type PushConfigRequest = Message<"everstack.controlplane.v1.PushConfigRequest"> & {
  /**
   * @generated from field: string instance_id = 1;
   */
  instanceId: string;

  /**
   * @generated from field: string section = 2;
   */
  section: string;

  /**
   * @generated from field: bytes config_json = 3;
   */
  configJson: Uint8Array;
};

/**
 * @generated from message everstack.controlplane.v1.PushConfigRequest
 */
export declare type PushConfigRequestJson = {
  /**
   * @generated from field: string instance_id = 1;
   */
  instanceId?: string;

  /**
   * @generated from field: string section = 2;
   */
  section?: string;

  /**
   * @generated from field: bytes config_json = 3;
   */
  configJson?: string;
};

/**
 * Describes the message everstack.controlplane.v1.PushConfigRequest.
 * Use `create(PushConfigRequestSchema)` to create a new message.
 */
export declare const PushConfigRequestSchema: GenMessage<PushConfigRequest, PushConfigRequestJson>;

/**
 * @generated from message everstack.controlplane.v1.PushConfigResponse
 */
export declare type PushConfigResponse = Message<"everstack.controlplane.v1.PushConfigResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * @generated from message everstack.controlplane.v1.PushConfigResponse
 */
export declare type PushConfigResponseJson = {
  /**
   * @generated from field: bool success = 1;
   */
  success?: boolean;
};

/**
 * Describes the message everstack.controlplane.v1.PushConfigResponse.
 * Use `create(PushConfigResponseSchema)` to create a new message.
 */
export declare const PushConfigResponseSchema: GenMessage<PushConfigResponse, PushConfigResponseJson>;

/**
 * @generated from message everstack.controlplane.v1.SetCustomDomainRequest
 */
export declare type SetCustomDomainRequest = Message<"everstack.controlplane.v1.SetCustomDomainRequest"> & {
  /**
   * @generated from field: string instance_id = 1;
   */
  instanceId: string;

  /**
   * @generated from field: string domain = 2;
   */
  domain: string;
};

/**
 * @generated from message everstack.controlplane.v1.SetCustomDomainRequest
 */
export declare type SetCustomDomainRequestJson = {
  /**
   * @generated from field: string instance_id = 1;
   */
  instanceId?: string;

  /**
   * @generated from field: string domain = 2;
   */
  domain?: string;
};

/**
 * Describes the message everstack.controlplane.v1.SetCustomDomainRequest.
 * Use `create(SetCustomDomainRequestSchema)` to create a new message.
 */
export declare const SetCustomDomainRequestSchema: GenMessage<SetCustomDomainRequest, SetCustomDomainRequestJson>;

/**
 * @generated from message everstack.controlplane.v1.SetCustomDomainResponse
 */
export declare type SetCustomDomainResponse = Message<"everstack.controlplane.v1.SetCustomDomainResponse"> & {
  /**
   * @generated from field: string domain = 1;
   */
  domain: string;

  /**
   * "pending_dns"
   *
   * @generated from field: string status = 2;
   */
  status: string;

  /**
   * e.g. "_everstack-verify.acme.com"
   *
   * @generated from field: string verification_txt_name = 3;
   */
  verificationTxtName: string;

  /**
   * random token tenant must publish
   *
   * @generated from field: string verification_txt_value = 4;
   */
  verificationTxtValue: string;

  /**
   * where the tenant should point CNAME
   *
   * @generated from field: string cname_target = 5;
   */
  cnameTarget: string;
};

/**
 * @generated from message everstack.controlplane.v1.SetCustomDomainResponse
 */
export declare type SetCustomDomainResponseJson = {
  /**
   * @generated from field: string domain = 1;
   */
  domain?: string;

  /**
   * "pending_dns"
   *
   * @generated from field: string status = 2;
   */
  status?: string;

  /**
   * e.g. "_everstack-verify.acme.com"
   *
   * @generated from field: string verification_txt_name = 3;
   */
  verificationTxtName?: string;

  /**
   * random token tenant must publish
   *
   * @generated from field: string verification_txt_value = 4;
   */
  verificationTxtValue?: string;

  /**
   * where the tenant should point CNAME
   *
   * @generated from field: string cname_target = 5;
   */
  cnameTarget?: string;
};

/**
 * Describes the message everstack.controlplane.v1.SetCustomDomainResponse.
 * Use `create(SetCustomDomainResponseSchema)` to create a new message.
 */
export declare const SetCustomDomainResponseSchema: GenMessage<SetCustomDomainResponse, SetCustomDomainResponseJson>;

/**
 * @generated from message everstack.controlplane.v1.VerifyCustomDomainRequest
 */
export declare type VerifyCustomDomainRequest = Message<"everstack.controlplane.v1.VerifyCustomDomainRequest"> & {
  /**
   * @generated from field: string instance_id = 1;
   */
  instanceId: string;
};

/**
 * @generated from message everstack.controlplane.v1.VerifyCustomDomainRequest
 */
export declare type VerifyCustomDomainRequestJson = {
  /**
   * @generated from field: string instance_id = 1;
   */
  instanceId?: string;
};

/**
 * Describes the message everstack.controlplane.v1.VerifyCustomDomainRequest.
 * Use `create(VerifyCustomDomainRequestSchema)` to create a new message.
 */
export declare const VerifyCustomDomainRequestSchema: GenMessage<VerifyCustomDomainRequest, VerifyCustomDomainRequestJson>;

/**
 * @generated from message everstack.controlplane.v1.VerifyCustomDomainResponse
 */
export declare type VerifyCustomDomainResponse = Message<"everstack.controlplane.v1.VerifyCustomDomainResponse"> & {
  /**
   * "pending_dns" | "verifying" | "active" | "failed"
   *
   * @generated from field: string status = 1;
   */
  status: string;

  /**
   * @generated from field: string message = 2;
   */
  message: string;
};

/**
 * @generated from message everstack.controlplane.v1.VerifyCustomDomainResponse
 */
export declare type VerifyCustomDomainResponseJson = {
  /**
   * "pending_dns" | "verifying" | "active" | "failed"
   *
   * @generated from field: string status = 1;
   */
  status?: string;

  /**
   * @generated from field: string message = 2;
   */
  message?: string;
};

/**
 * Describes the message everstack.controlplane.v1.VerifyCustomDomainResponse.
 * Use `create(VerifyCustomDomainResponseSchema)` to create a new message.
 */
export declare const VerifyCustomDomainResponseSchema: GenMessage<VerifyCustomDomainResponse, VerifyCustomDomainResponseJson>;

/**
 * @generated from message everstack.controlplane.v1.RemoveCustomDomainRequest
 */
export declare type RemoveCustomDomainRequest = Message<"everstack.controlplane.v1.RemoveCustomDomainRequest"> & {
  /**
   * @generated from field: string instance_id = 1;
   */
  instanceId: string;
};

/**
 * @generated from message everstack.controlplane.v1.RemoveCustomDomainRequest
 */
export declare type RemoveCustomDomainRequestJson = {
  /**
   * @generated from field: string instance_id = 1;
   */
  instanceId?: string;
};

/**
 * Describes the message everstack.controlplane.v1.RemoveCustomDomainRequest.
 * Use `create(RemoveCustomDomainRequestSchema)` to create a new message.
 */
export declare const RemoveCustomDomainRequestSchema: GenMessage<RemoveCustomDomainRequest, RemoveCustomDomainRequestJson>;

/**
 * @generated from message everstack.controlplane.v1.RemoveCustomDomainResponse
 */
export declare type RemoveCustomDomainResponse = Message<"everstack.controlplane.v1.RemoveCustomDomainResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * @generated from message everstack.controlplane.v1.RemoveCustomDomainResponse
 */
export declare type RemoveCustomDomainResponseJson = {
  /**
   * @generated from field: bool success = 1;
   */
  success?: boolean;
};

/**
 * Describes the message everstack.controlplane.v1.RemoveCustomDomainResponse.
 * Use `create(RemoveCustomDomainResponseSchema)` to create a new message.
 */
export declare const RemoveCustomDomainResponseSchema: GenMessage<RemoveCustomDomainResponse, RemoveCustomDomainResponseJson>;

/**
 * InstanceStatus represents the lifecycle state of a managed gateway instance.
 *
 * @generated from enum everstack.controlplane.v1.InstanceStatus
 */
export enum InstanceStatus {
  /**
   * @generated from enum value: INSTANCE_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: INSTANCE_STATUS_PROVISIONING = 1;
   */
  PROVISIONING = 1,

  /**
   * @generated from enum value: INSTANCE_STATUS_STARTING = 2;
   */
  STARTING = 2,

  /**
   * @generated from enum value: INSTANCE_STATUS_RUNNING = 3;
   */
  RUNNING = 3,

  /**
   * @generated from enum value: INSTANCE_STATUS_STOPPING = 4;
   */
  STOPPING = 4,

  /**
   * @generated from enum value: INSTANCE_STATUS_STOPPED = 5;
   */
  STOPPED = 5,

  /**
   * @generated from enum value: INSTANCE_STATUS_DEGRADED = 6;
   */
  DEGRADED = 6,

  /**
   * @generated from enum value: INSTANCE_STATUS_FAILED = 7;
   */
  FAILED = 7,

  /**
   * @generated from enum value: INSTANCE_STATUS_DELETING = 8;
   */
  DELETING = 8,
}

/**
 * InstanceStatus represents the lifecycle state of a managed gateway instance.
 *
 * @generated from enum everstack.controlplane.v1.InstanceStatus
 */
export declare type InstanceStatusJson = "INSTANCE_STATUS_UNSPECIFIED" | "INSTANCE_STATUS_PROVISIONING" | "INSTANCE_STATUS_STARTING" | "INSTANCE_STATUS_RUNNING" | "INSTANCE_STATUS_STOPPING" | "INSTANCE_STATUS_STOPPED" | "INSTANCE_STATUS_DEGRADED" | "INSTANCE_STATUS_FAILED" | "INSTANCE_STATUS_DELETING";

/**
 * Describes the enum everstack.controlplane.v1.InstanceStatus.
 */
export declare const InstanceStatusSchema: GenEnum<InstanceStatus, InstanceStatusJson>;

