// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: everstack/license/v1/features_service.proto

package licenseconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/everstacklabs/everstack/pkg/grpc/everstack/license/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// FeatureManagementServiceName is the fully-qualified name of the FeatureManagementService service.
	FeatureManagementServiceName = "everstack.license.v1.FeatureManagementService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FeatureManagementServiceListFeaturesProcedure is the fully-qualified name of the
	// FeatureManagementService's ListFeatures RPC.
	FeatureManagementServiceListFeaturesProcedure = "/everstack.license.v1.FeatureManagementService/ListFeatures"
	// FeatureManagementServiceGetFeatureProcedure is the fully-qualified name of the
	// FeatureManagementService's GetFeature RPC.
	FeatureManagementServiceGetFeatureProcedure = "/everstack.license.v1.FeatureManagementService/GetFeature"
	// FeatureManagementServiceCreateFeatureProcedure is the fully-qualified name of the
	// FeatureManagementService's CreateFeature RPC.
	FeatureManagementServiceCreateFeatureProcedure = "/everstack.license.v1.FeatureManagementService/CreateFeature"
	// FeatureManagementServiceUpdateFeatureProcedure is the fully-qualified name of the
	// FeatureManagementService's UpdateFeature RPC.
	FeatureManagementServiceUpdateFeatureProcedure = "/everstack.license.v1.FeatureManagementService/UpdateFeature"
	// FeatureManagementServiceDeleteFeatureProcedure is the fully-qualified name of the
	// FeatureManagementService's DeleteFeature RPC.
	FeatureManagementServiceDeleteFeatureProcedure = "/everstack.license.v1.FeatureManagementService/DeleteFeature"
	// FeatureManagementServiceListTenantOverridesProcedure is the fully-qualified name of the
	// FeatureManagementService's ListTenantOverrides RPC.
	FeatureManagementServiceListTenantOverridesProcedure = "/everstack.license.v1.FeatureManagementService/ListTenantOverrides"
	// FeatureManagementServiceSetTenantOverrideProcedure is the fully-qualified name of the
	// FeatureManagementService's SetTenantOverride RPC.
	FeatureManagementServiceSetTenantOverrideProcedure = "/everstack.license.v1.FeatureManagementService/SetTenantOverride"
	// FeatureManagementServiceDeleteTenantOverrideProcedure is the fully-qualified name of the
	// FeatureManagementService's DeleteTenantOverride RPC.
	FeatureManagementServiceDeleteTenantOverrideProcedure = "/everstack.license.v1.FeatureManagementService/DeleteTenantOverride"
	// FeatureManagementServiceForcePublishManifestProcedure is the fully-qualified name of the
	// FeatureManagementService's ForcePublishManifest RPC.
	FeatureManagementServiceForcePublishManifestProcedure = "/everstack.license.v1.FeatureManagementService/ForcePublishManifest"
)

// FeatureManagementServiceClient is a client for the everstack.license.v1.FeatureManagementService
// service.
type FeatureManagementServiceClient interface {
	// ListFeatures returns all feature definitions
	ListFeatures(context.Context, *connect.Request[v1.ListFeaturesRequest]) (*connect.Response[v1.ListFeaturesResponse], error)
	// GetFeature returns a single feature definition
	GetFeature(context.Context, *connect.Request[v1.GetFeatureRequest]) (*connect.Response[v1.GetFeatureResponse], error)
	// CreateFeature adds a new feature definition (no rebuild needed!)
	CreateFeature(context.Context, *connect.Request[v1.CreateFeatureRequest]) (*connect.Response[v1.CreateFeatureResponse], error)
	// UpdateFeature modifies an existing feature definition
	UpdateFeature(context.Context, *connect.Request[v1.UpdateFeatureRequest]) (*connect.Response[v1.UpdateFeatureResponse], error)
	// DeleteFeature removes a feature definition and all its overrides
	DeleteFeature(context.Context, *connect.Request[v1.DeleteFeatureRequest]) (*connect.Response[v1.DeleteFeatureResponse], error)
	// ListTenantOverrides returns all overrides for a specific tenant
	ListTenantOverrides(context.Context, *connect.Request[v1.ListTenantOverridesRequest]) (*connect.Response[v1.ListTenantOverridesResponse], error)
	// SetTenantOverride creates or updates a feature override for a tenant
	SetTenantOverride(context.Context, *connect.Request[v1.SetTenantOverrideRequest]) (*connect.Response[v1.SetTenantOverrideResponse], error)
	// DeleteTenantOverride removes a feature override for a tenant
	DeleteTenantOverride(context.Context, *connect.Request[v1.DeleteTenantOverrideRequest]) (*connect.Response[v1.DeleteTenantOverrideResponse], error)
	// ForcePublishManifest triggers immediate manifest generation and KV publish
	ForcePublishManifest(context.Context, *connect.Request[v1.ForcePublishManifestRequest]) (*connect.Response[v1.ForcePublishManifestResponse], error)
}

// NewFeatureManagementServiceClient constructs a client for the
// everstack.license.v1.FeatureManagementService service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFeatureManagementServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FeatureManagementServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	featureManagementServiceMethods := v1.File_everstack_license_v1_features_service_proto.Services().ByName("FeatureManagementService").Methods()
	return &featureManagementServiceClient{
		listFeatures: connect.NewClient[v1.ListFeaturesRequest, v1.ListFeaturesResponse](
			httpClient,
			baseURL+FeatureManagementServiceListFeaturesProcedure,
			connect.WithSchema(featureManagementServiceMethods.ByName("ListFeatures")),
			connect.WithClientOptions(opts...),
		),
		getFeature: connect.NewClient[v1.GetFeatureRequest, v1.GetFeatureResponse](
			httpClient,
			baseURL+FeatureManagementServiceGetFeatureProcedure,
			connect.WithSchema(featureManagementServiceMethods.ByName("GetFeature")),
			connect.WithClientOptions(opts...),
		),
		createFeature: connect.NewClient[v1.CreateFeatureRequest, v1.CreateFeatureResponse](
			httpClient,
			baseURL+FeatureManagementServiceCreateFeatureProcedure,
			connect.WithSchema(featureManagementServiceMethods.ByName("CreateFeature")),
			connect.WithClientOptions(opts...),
		),
		updateFeature: connect.NewClient[v1.UpdateFeatureRequest, v1.UpdateFeatureResponse](
			httpClient,
			baseURL+FeatureManagementServiceUpdateFeatureProcedure,
			connect.WithSchema(featureManagementServiceMethods.ByName("UpdateFeature")),
			connect.WithClientOptions(opts...),
		),
		deleteFeature: connect.NewClient[v1.DeleteFeatureRequest, v1.DeleteFeatureResponse](
			httpClient,
			baseURL+FeatureManagementServiceDeleteFeatureProcedure,
			connect.WithSchema(featureManagementServiceMethods.ByName("DeleteFeature")),
			connect.WithClientOptions(opts...),
		),
		listTenantOverrides: connect.NewClient[v1.ListTenantOverridesRequest, v1.ListTenantOverridesResponse](
			httpClient,
			baseURL+FeatureManagementServiceListTenantOverridesProcedure,
			connect.WithSchema(featureManagementServiceMethods.ByName("ListTenantOverrides")),
			connect.WithClientOptions(opts...),
		),
		setTenantOverride: connect.NewClient[v1.SetTenantOverrideRequest, v1.SetTenantOverrideResponse](
			httpClient,
			baseURL+FeatureManagementServiceSetTenantOverrideProcedure,
			connect.WithSchema(featureManagementServiceMethods.ByName("SetTenantOverride")),
			connect.WithClientOptions(opts...),
		),
		deleteTenantOverride: connect.NewClient[v1.DeleteTenantOverrideRequest, v1.DeleteTenantOverrideResponse](
			httpClient,
			baseURL+FeatureManagementServiceDeleteTenantOverrideProcedure,
			connect.WithSchema(featureManagementServiceMethods.ByName("DeleteTenantOverride")),
			connect.WithClientOptions(opts...),
		),
		forcePublishManifest: connect.NewClient[v1.ForcePublishManifestRequest, v1.ForcePublishManifestResponse](
			httpClient,
			baseURL+FeatureManagementServiceForcePublishManifestProcedure,
			connect.WithSchema(featureManagementServiceMethods.ByName("ForcePublishManifest")),
			connect.WithClientOptions(opts...),
		),
	}
}

// featureManagementServiceClient implements FeatureManagementServiceClient.
type featureManagementServiceClient struct {
	listFeatures         *connect.Client[v1.ListFeaturesRequest, v1.ListFeaturesResponse]
	getFeature           *connect.Client[v1.GetFeatureRequest, v1.GetFeatureResponse]
	createFeature        *connect.Client[v1.CreateFeatureRequest, v1.CreateFeatureResponse]
	updateFeature        *connect.Client[v1.UpdateFeatureRequest, v1.UpdateFeatureResponse]
	deleteFeature        *connect.Client[v1.DeleteFeatureRequest, v1.DeleteFeatureResponse]
	listTenantOverrides  *connect.Client[v1.ListTenantOverridesRequest, v1.ListTenantOverridesResponse]
	setTenantOverride    *connect.Client[v1.SetTenantOverrideRequest, v1.SetTenantOverrideResponse]
	deleteTenantOverride *connect.Client[v1.DeleteTenantOverrideRequest, v1.DeleteTenantOverrideResponse]
	forcePublishManifest *connect.Client[v1.ForcePublishManifestRequest, v1.ForcePublishManifestResponse]
}

// ListFeatures calls everstack.license.v1.FeatureManagementService.ListFeatures.
func (c *featureManagementServiceClient) ListFeatures(ctx context.Context, req *connect.Request[v1.ListFeaturesRequest]) (*connect.Response[v1.ListFeaturesResponse], error) {
	return c.listFeatures.CallUnary(ctx, req)
}

// GetFeature calls everstack.license.v1.FeatureManagementService.GetFeature.
func (c *featureManagementServiceClient) GetFeature(ctx context.Context, req *connect.Request[v1.GetFeatureRequest]) (*connect.Response[v1.GetFeatureResponse], error) {
	return c.getFeature.CallUnary(ctx, req)
}

// CreateFeature calls everstack.license.v1.FeatureManagementService.CreateFeature.
func (c *featureManagementServiceClient) CreateFeature(ctx context.Context, req *connect.Request[v1.CreateFeatureRequest]) (*connect.Response[v1.CreateFeatureResponse], error) {
	return c.createFeature.CallUnary(ctx, req)
}

// UpdateFeature calls everstack.license.v1.FeatureManagementService.UpdateFeature.
func (c *featureManagementServiceClient) UpdateFeature(ctx context.Context, req *connect.Request[v1.UpdateFeatureRequest]) (*connect.Response[v1.UpdateFeatureResponse], error) {
	return c.updateFeature.CallUnary(ctx, req)
}

// DeleteFeature calls everstack.license.v1.FeatureManagementService.DeleteFeature.
func (c *featureManagementServiceClient) DeleteFeature(ctx context.Context, req *connect.Request[v1.DeleteFeatureRequest]) (*connect.Response[v1.DeleteFeatureResponse], error) {
	return c.deleteFeature.CallUnary(ctx, req)
}

// ListTenantOverrides calls everstack.license.v1.FeatureManagementService.ListTenantOverrides.
func (c *featureManagementServiceClient) ListTenantOverrides(ctx context.Context, req *connect.Request[v1.ListTenantOverridesRequest]) (*connect.Response[v1.ListTenantOverridesResponse], error) {
	return c.listTenantOverrides.CallUnary(ctx, req)
}

// SetTenantOverride calls everstack.license.v1.FeatureManagementService.SetTenantOverride.
func (c *featureManagementServiceClient) SetTenantOverride(ctx context.Context, req *connect.Request[v1.SetTenantOverrideRequest]) (*connect.Response[v1.SetTenantOverrideResponse], error) {
	return c.setTenantOverride.CallUnary(ctx, req)
}

// DeleteTenantOverride calls everstack.license.v1.FeatureManagementService.DeleteTenantOverride.
func (c *featureManagementServiceClient) DeleteTenantOverride(ctx context.Context, req *connect.Request[v1.DeleteTenantOverrideRequest]) (*connect.Response[v1.DeleteTenantOverrideResponse], error) {
	return c.deleteTenantOverride.CallUnary(ctx, req)
}

// ForcePublishManifest calls everstack.license.v1.FeatureManagementService.ForcePublishManifest.
func (c *featureManagementServiceClient) ForcePublishManifest(ctx context.Context, req *connect.Request[v1.ForcePublishManifestRequest]) (*connect.Response[v1.ForcePublishManifestResponse], error) {
	return c.forcePublishManifest.CallUnary(ctx, req)
}

// FeatureManagementServiceHandler is an implementation of the
// everstack.license.v1.FeatureManagementService service.
type FeatureManagementServiceHandler interface {
	// ListFeatures returns all feature definitions
	ListFeatures(context.Context, *connect.Request[v1.ListFeaturesRequest]) (*connect.Response[v1.ListFeaturesResponse], error)
	// GetFeature returns a single feature definition
	GetFeature(context.Context, *connect.Request[v1.GetFeatureRequest]) (*connect.Response[v1.GetFeatureResponse], error)
	// CreateFeature adds a new feature definition (no rebuild needed!)
	CreateFeature(context.Context, *connect.Request[v1.CreateFeatureRequest]) (*connect.Response[v1.CreateFeatureResponse], error)
	// UpdateFeature modifies an existing feature definition
	UpdateFeature(context.Context, *connect.Request[v1.UpdateFeatureRequest]) (*connect.Response[v1.UpdateFeatureResponse], error)
	// DeleteFeature removes a feature definition and all its overrides
	DeleteFeature(context.Context, *connect.Request[v1.DeleteFeatureRequest]) (*connect.Response[v1.DeleteFeatureResponse], error)
	// ListTenantOverrides returns all overrides for a specific tenant
	ListTenantOverrides(context.Context, *connect.Request[v1.ListTenantOverridesRequest]) (*connect.Response[v1.ListTenantOverridesResponse], error)
	// SetTenantOverride creates or updates a feature override for a tenant
	SetTenantOverride(context.Context, *connect.Request[v1.SetTenantOverrideRequest]) (*connect.Response[v1.SetTenantOverrideResponse], error)
	// DeleteTenantOverride removes a feature override for a tenant
	DeleteTenantOverride(context.Context, *connect.Request[v1.DeleteTenantOverrideRequest]) (*connect.Response[v1.DeleteTenantOverrideResponse], error)
	// ForcePublishManifest triggers immediate manifest generation and KV publish
	ForcePublishManifest(context.Context, *connect.Request[v1.ForcePublishManifestRequest]) (*connect.Response[v1.ForcePublishManifestResponse], error)
}

// NewFeatureManagementServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFeatureManagementServiceHandler(svc FeatureManagementServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	featureManagementServiceMethods := v1.File_everstack_license_v1_features_service_proto.Services().ByName("FeatureManagementService").Methods()
	featureManagementServiceListFeaturesHandler := connect.NewUnaryHandler(
		FeatureManagementServiceListFeaturesProcedure,
		svc.ListFeatures,
		connect.WithSchema(featureManagementServiceMethods.ByName("ListFeatures")),
		connect.WithHandlerOptions(opts...),
	)
	featureManagementServiceGetFeatureHandler := connect.NewUnaryHandler(
		FeatureManagementServiceGetFeatureProcedure,
		svc.GetFeature,
		connect.WithSchema(featureManagementServiceMethods.ByName("GetFeature")),
		connect.WithHandlerOptions(opts...),
	)
	featureManagementServiceCreateFeatureHandler := connect.NewUnaryHandler(
		FeatureManagementServiceCreateFeatureProcedure,
		svc.CreateFeature,
		connect.WithSchema(featureManagementServiceMethods.ByName("CreateFeature")),
		connect.WithHandlerOptions(opts...),
	)
	featureManagementServiceUpdateFeatureHandler := connect.NewUnaryHandler(
		FeatureManagementServiceUpdateFeatureProcedure,
		svc.UpdateFeature,
		connect.WithSchema(featureManagementServiceMethods.ByName("UpdateFeature")),
		connect.WithHandlerOptions(opts...),
	)
	featureManagementServiceDeleteFeatureHandler := connect.NewUnaryHandler(
		FeatureManagementServiceDeleteFeatureProcedure,
		svc.DeleteFeature,
		connect.WithSchema(featureManagementServiceMethods.ByName("DeleteFeature")),
		connect.WithHandlerOptions(opts...),
	)
	featureManagementServiceListTenantOverridesHandler := connect.NewUnaryHandler(
		FeatureManagementServiceListTenantOverridesProcedure,
		svc.ListTenantOverrides,
		connect.WithSchema(featureManagementServiceMethods.ByName("ListTenantOverrides")),
		connect.WithHandlerOptions(opts...),
	)
	featureManagementServiceSetTenantOverrideHandler := connect.NewUnaryHandler(
		FeatureManagementServiceSetTenantOverrideProcedure,
		svc.SetTenantOverride,
		connect.WithSchema(featureManagementServiceMethods.ByName("SetTenantOverride")),
		connect.WithHandlerOptions(opts...),
	)
	featureManagementServiceDeleteTenantOverrideHandler := connect.NewUnaryHandler(
		FeatureManagementServiceDeleteTenantOverrideProcedure,
		svc.DeleteTenantOverride,
		connect.WithSchema(featureManagementServiceMethods.ByName("DeleteTenantOverride")),
		connect.WithHandlerOptions(opts...),
	)
	featureManagementServiceForcePublishManifestHandler := connect.NewUnaryHandler(
		FeatureManagementServiceForcePublishManifestProcedure,
		svc.ForcePublishManifest,
		connect.WithSchema(featureManagementServiceMethods.ByName("ForcePublishManifest")),
		connect.WithHandlerOptions(opts...),
	)
	return "/everstack.license.v1.FeatureManagementService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FeatureManagementServiceListFeaturesProcedure:
			featureManagementServiceListFeaturesHandler.ServeHTTP(w, r)
		case FeatureManagementServiceGetFeatureProcedure:
			featureManagementServiceGetFeatureHandler.ServeHTTP(w, r)
		case FeatureManagementServiceCreateFeatureProcedure:
			featureManagementServiceCreateFeatureHandler.ServeHTTP(w, r)
		case FeatureManagementServiceUpdateFeatureProcedure:
			featureManagementServiceUpdateFeatureHandler.ServeHTTP(w, r)
		case FeatureManagementServiceDeleteFeatureProcedure:
			featureManagementServiceDeleteFeatureHandler.ServeHTTP(w, r)
		case FeatureManagementServiceListTenantOverridesProcedure:
			featureManagementServiceListTenantOverridesHandler.ServeHTTP(w, r)
		case FeatureManagementServiceSetTenantOverrideProcedure:
			featureManagementServiceSetTenantOverrideHandler.ServeHTTP(w, r)
		case FeatureManagementServiceDeleteTenantOverrideProcedure:
			featureManagementServiceDeleteTenantOverrideHandler.ServeHTTP(w, r)
		case FeatureManagementServiceForcePublishManifestProcedure:
			featureManagementServiceForcePublishManifestHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFeatureManagementServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFeatureManagementServiceHandler struct{}

func (UnimplementedFeatureManagementServiceHandler) ListFeatures(context.Context, *connect.Request[v1.ListFeaturesRequest]) (*connect.Response[v1.ListFeaturesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("everstack.license.v1.FeatureManagementService.ListFeatures is not implemented"))
}

func (UnimplementedFeatureManagementServiceHandler) GetFeature(context.Context, *connect.Request[v1.GetFeatureRequest]) (*connect.Response[v1.GetFeatureResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("everstack.license.v1.FeatureManagementService.GetFeature is not implemented"))
}

func (UnimplementedFeatureManagementServiceHandler) CreateFeature(context.Context, *connect.Request[v1.CreateFeatureRequest]) (*connect.Response[v1.CreateFeatureResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("everstack.license.v1.FeatureManagementService.CreateFeature is not implemented"))
}

func (UnimplementedFeatureManagementServiceHandler) UpdateFeature(context.Context, *connect.Request[v1.UpdateFeatureRequest]) (*connect.Response[v1.UpdateFeatureResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("everstack.license.v1.FeatureManagementService.UpdateFeature is not implemented"))
}

func (UnimplementedFeatureManagementServiceHandler) DeleteFeature(context.Context, *connect.Request[v1.DeleteFeatureRequest]) (*connect.Response[v1.DeleteFeatureResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("everstack.license.v1.FeatureManagementService.DeleteFeature is not implemented"))
}

func (UnimplementedFeatureManagementServiceHandler) ListTenantOverrides(context.Context, *connect.Request[v1.ListTenantOverridesRequest]) (*connect.Response[v1.ListTenantOverridesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("everstack.license.v1.FeatureManagementService.ListTenantOverrides is not implemented"))
}

func (UnimplementedFeatureManagementServiceHandler) SetTenantOverride(context.Context, *connect.Request[v1.SetTenantOverrideRequest]) (*connect.Response[v1.SetTenantOverrideResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("everstack.license.v1.FeatureManagementService.SetTenantOverride is not implemented"))
}

func (UnimplementedFeatureManagementServiceHandler) DeleteTenantOverride(context.Context, *connect.Request[v1.DeleteTenantOverrideRequest]) (*connect.Response[v1.DeleteTenantOverrideResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("everstack.license.v1.FeatureManagementService.DeleteTenantOverride is not implemented"))
}

func (UnimplementedFeatureManagementServiceHandler) ForcePublishManifest(context.Context, *connect.Request[v1.ForcePublishManifestRequest]) (*connect.Response[v1.ForcePublishManifestResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("everstack.license.v1.FeatureManagementService.ForcePublishManifest is not implemented"))
}
