// @generated by protoc-gen-es v2.2.0 with parameter "target=dts,json_types=true,import_extension=js"
// @generated from file everstack/prompts/v1/prompts_service.proto (package everstack.prompts.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv1";
import type { CreatePromptRequestSchema, CreatePromptResponseSchema, CreatePromptVersionRequestSchema, CreatePromptVersionResponseSchema, DeletePromptRequestSchema, DeletePromptResponseSchema, GetPromptRequestSchema, GetPromptResponseSchema, GetPromptVersionRequestSchema, GetPromptVersionResponseSchema, ListPromptsRequestSchema, ListPromptsResponseSchema, ListPromptVersionsRequestSchema, ListPromptVersionsResponseSchema, SetPromptLabelsRequestSchema, SetPromptLabelsResponseSchema, UpdatePromptRequestSchema, UpdatePromptResponseSchema } from "./prompts_pb.js";

/**
 * Describes the file everstack/prompts/v1/prompts_service.proto.
 */
export declare const file_everstack_prompts_v1_prompts_service: GenFile;

/**
 * PromptService manages versioned prompt templates for the prompt library
 * and playground. Tenant scoping is enforced server-side from the request
 * context; client-supplied tenant ids are never accepted.
 *
 * --- Prompts ---
 *
 * @generated from service everstack.prompts.v1.PromptService
 */
export declare const PromptService: GenService<{
  /**
   * @generated from rpc everstack.prompts.v1.PromptService.CreatePrompt
   */
  createPrompt: {
    methodKind: "unary";
    input: typeof CreatePromptRequestSchema;
    output: typeof CreatePromptResponseSchema;
  },
  /**
   * @generated from rpc everstack.prompts.v1.PromptService.GetPrompt
   */
  getPrompt: {
    methodKind: "unary";
    input: typeof GetPromptRequestSchema;
    output: typeof GetPromptResponseSchema;
  },
  /**
   * @generated from rpc everstack.prompts.v1.PromptService.ListPrompts
   */
  listPrompts: {
    methodKind: "unary";
    input: typeof ListPromptsRequestSchema;
    output: typeof ListPromptsResponseSchema;
  },
  /**
   * @generated from rpc everstack.prompts.v1.PromptService.UpdatePrompt
   */
  updatePrompt: {
    methodKind: "unary";
    input: typeof UpdatePromptRequestSchema;
    output: typeof UpdatePromptResponseSchema;
  },
  /**
   * @generated from rpc everstack.prompts.v1.PromptService.DeletePrompt
   */
  deletePrompt: {
    methodKind: "unary";
    input: typeof DeletePromptRequestSchema;
    output: typeof DeletePromptResponseSchema;
  },
  /**
   * @generated from rpc everstack.prompts.v1.PromptService.CreatePromptVersion
   */
  createPromptVersion: {
    methodKind: "unary";
    input: typeof CreatePromptVersionRequestSchema;
    output: typeof CreatePromptVersionResponseSchema;
  },
  /**
   * @generated from rpc everstack.prompts.v1.PromptService.ListPromptVersions
   */
  listPromptVersions: {
    methodKind: "unary";
    input: typeof ListPromptVersionsRequestSchema;
    output: typeof ListPromptVersionsResponseSchema;
  },
  /**
   * @generated from rpc everstack.prompts.v1.PromptService.GetPromptVersion
   */
  getPromptVersion: {
    methodKind: "unary";
    input: typeof GetPromptVersionRequestSchema;
    output: typeof GetPromptVersionResponseSchema;
  },
  /**
   * @generated from rpc everstack.prompts.v1.PromptService.SetPromptLabels
   */
  setPromptLabels: {
    methodKind: "unary";
    input: typeof SetPromptLabelsRequestSchema;
    output: typeof SetPromptLabelsResponseSchema;
  },
}>;

