// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: everstack/catalog/v1/catalog.proto

package catalog

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetCatalogStatusRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetCatalogStatusRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetCatalogStatusRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetCatalogStatusRequestMultiError, or nil if none found.
func (m *GetCatalogStatusRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetCatalogStatusRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetCatalogStatusRequestMultiError(errors)
	}

	return nil
}

// GetCatalogStatusRequestMultiError is an error wrapping multiple validation
// errors returned by GetCatalogStatusRequest.ValidateAll() if the designated
// constraints aren't met.
type GetCatalogStatusRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetCatalogStatusRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetCatalogStatusRequestMultiError) AllErrors() []error { return m }

// GetCatalogStatusRequestValidationError is the validation error returned by
// GetCatalogStatusRequest.Validate if the designated constraints aren't met.
type GetCatalogStatusRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetCatalogStatusRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetCatalogStatusRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetCatalogStatusRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetCatalogStatusRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetCatalogStatusRequestValidationError) ErrorName() string {
	return "GetCatalogStatusRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetCatalogStatusRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetCatalogStatusRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetCatalogStatusRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetCatalogStatusRequestValidationError{}

// Validate checks the field values on GetChangelogRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetChangelogRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetChangelogRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetChangelogRequestMultiError, or nil if none found.
func (m *GetChangelogRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetChangelogRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for FromVersion

	if len(errors) > 0 {
		return GetChangelogRequestMultiError(errors)
	}

	return nil
}

// GetChangelogRequestMultiError is an error wrapping multiple validation
// errors returned by GetChangelogRequest.ValidateAll() if the designated
// constraints aren't met.
type GetChangelogRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetChangelogRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetChangelogRequestMultiError) AllErrors() []error { return m }

// GetChangelogRequestValidationError is the validation error returned by
// GetChangelogRequest.Validate if the designated constraints aren't met.
type GetChangelogRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetChangelogRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetChangelogRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetChangelogRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetChangelogRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetChangelogRequestValidationError) ErrorName() string {
	return "GetChangelogRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetChangelogRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetChangelogRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetChangelogRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetChangelogRequestValidationError{}

// Validate checks the field values on GetNewModelsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetNewModelsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetNewModelsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetNewModelsRequestMultiError, or nil if none found.
func (m *GetNewModelsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetNewModelsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Provider

	if len(errors) > 0 {
		return GetNewModelsRequestMultiError(errors)
	}

	return nil
}

// GetNewModelsRequestMultiError is an error wrapping multiple validation
// errors returned by GetNewModelsRequest.ValidateAll() if the designated
// constraints aren't met.
type GetNewModelsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetNewModelsRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetNewModelsRequestMultiError) AllErrors() []error { return m }

// GetNewModelsRequestValidationError is the validation error returned by
// GetNewModelsRequest.Validate if the designated constraints aren't met.
type GetNewModelsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetNewModelsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetNewModelsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetNewModelsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetNewModelsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetNewModelsRequestValidationError) ErrorName() string {
	return "GetNewModelsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetNewModelsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetNewModelsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetNewModelsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetNewModelsRequestValidationError{}

// Validate checks the field values on TriggerSyncRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *TriggerSyncRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TriggerSyncRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TriggerSyncRequestMultiError, or nil if none found.
func (m *TriggerSyncRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *TriggerSyncRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Force

	if len(errors) > 0 {
		return TriggerSyncRequestMultiError(errors)
	}

	return nil
}

// TriggerSyncRequestMultiError is an error wrapping multiple validation errors
// returned by TriggerSyncRequest.ValidateAll() if the designated constraints
// aren't met.
type TriggerSyncRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TriggerSyncRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TriggerSyncRequestMultiError) AllErrors() []error { return m }

// TriggerSyncRequestValidationError is the validation error returned by
// TriggerSyncRequest.Validate if the designated constraints aren't met.
type TriggerSyncRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TriggerSyncRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TriggerSyncRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TriggerSyncRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TriggerSyncRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TriggerSyncRequestValidationError) ErrorName() string {
	return "TriggerSyncRequestValidationError"
}

// Error satisfies the builtin error interface
func (e TriggerSyncRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTriggerSyncRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TriggerSyncRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TriggerSyncRequestValidationError{}

// Validate checks the field values on CatalogStatus with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *CatalogStatus) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CatalogStatus with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in CatalogStatusMultiError, or
// nil if none found.
func (m *CatalogStatus) ValidateAll() error {
	return m.validate(true)
}

func (m *CatalogStatus) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CurrentVersion

	// no validation rules for RemoteVersion

	// no validation rules for LastCheck

	// no validation rules for SyncEnabled

	// no validation rules for SyncUrl

	// no validation rules for NewModelsCount

	// no validation rules for NewProvidersCount

	// no validation rules for LastSync

	// no validation rules for HasUpdates

	if len(errors) > 0 {
		return CatalogStatusMultiError(errors)
	}

	return nil
}

// CatalogStatusMultiError is an error wrapping multiple validation errors
// returned by CatalogStatus.ValidateAll() if the designated constraints
// aren't met.
type CatalogStatusMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CatalogStatusMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CatalogStatusMultiError) AllErrors() []error { return m }

// CatalogStatusValidationError is the validation error returned by
// CatalogStatus.Validate if the designated constraints aren't met.
type CatalogStatusValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CatalogStatusValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CatalogStatusValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CatalogStatusValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CatalogStatusValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CatalogStatusValidationError) ErrorName() string { return "CatalogStatusValidationError" }

// Error satisfies the builtin error interface
func (e CatalogStatusValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCatalogStatus.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CatalogStatusValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CatalogStatusValidationError{}

// Validate checks the field values on ChangelogEntry with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ChangelogEntry) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ChangelogEntry with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ChangelogEntryMultiError,
// or nil if none found.
func (m *ChangelogEntry) ValidateAll() error {
	return m.validate(true)
}

func (m *ChangelogEntry) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Version

	// no validation rules for Date

	// no validation rules for Description

	if len(errors) > 0 {
		return ChangelogEntryMultiError(errors)
	}

	return nil
}

// ChangelogEntryMultiError is an error wrapping multiple validation errors
// returned by ChangelogEntry.ValidateAll() if the designated constraints
// aren't met.
type ChangelogEntryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ChangelogEntryMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ChangelogEntryMultiError) AllErrors() []error { return m }

// ChangelogEntryValidationError is the validation error returned by
// ChangelogEntry.Validate if the designated constraints aren't met.
type ChangelogEntryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ChangelogEntryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ChangelogEntryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ChangelogEntryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ChangelogEntryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ChangelogEntryValidationError) ErrorName() string { return "ChangelogEntryValidationError" }

// Error satisfies the builtin error interface
func (e ChangelogEntryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sChangelogEntry.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ChangelogEntryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ChangelogEntryValidationError{}

// Validate checks the field values on Changelog with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Changelog) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Changelog with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ChangelogMultiError, or nil
// if none found.
func (m *Changelog) ValidateAll() error {
	return m.validate(true)
}

func (m *Changelog) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetEntries() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ChangelogValidationError{
						field:  fmt.Sprintf("Entries[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ChangelogValidationError{
						field:  fmt.Sprintf("Entries[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ChangelogValidationError{
					field:  fmt.Sprintf("Entries[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ChangelogMultiError(errors)
	}

	return nil
}

// ChangelogMultiError is an error wrapping multiple validation errors returned
// by Changelog.ValidateAll() if the designated constraints aren't met.
type ChangelogMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ChangelogMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ChangelogMultiError) AllErrors() []error { return m }

// ChangelogValidationError is the validation error returned by
// Changelog.Validate if the designated constraints aren't met.
type ChangelogValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ChangelogValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ChangelogValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ChangelogValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ChangelogValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ChangelogValidationError) ErrorName() string { return "ChangelogValidationError" }

// Error satisfies the builtin error interface
func (e ChangelogValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sChangelog.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ChangelogValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ChangelogValidationError{}

// Validate checks the field values on NewModel with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *NewModel) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NewModel with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in NewModelMultiError, or nil
// if none found.
func (m *NewModel) ValidateAll() error {
	return m.validate(true)
}

func (m *NewModel) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Provider

	// no validation rules for Name

	// no validation rules for DisplayName

	// no validation rules for MaxTokens

	// no validation rules for InputCostPer_1K

	// no validation rules for OutputCostPer_1K

	// no validation rules for Status

	if len(errors) > 0 {
		return NewModelMultiError(errors)
	}

	return nil
}

// NewModelMultiError is an error wrapping multiple validation errors returned
// by NewModel.ValidateAll() if the designated constraints aren't met.
type NewModelMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NewModelMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NewModelMultiError) AllErrors() []error { return m }

// NewModelValidationError is the validation error returned by
// NewModel.Validate if the designated constraints aren't met.
type NewModelValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NewModelValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NewModelValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NewModelValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NewModelValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NewModelValidationError) ErrorName() string { return "NewModelValidationError" }

// Error satisfies the builtin error interface
func (e NewModelValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNewModel.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NewModelValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NewModelValidationError{}

// Validate checks the field values on NewModels with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *NewModels) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NewModels with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in NewModelsMultiError, or nil
// if none found.
func (m *NewModels) ValidateAll() error {
	return m.validate(true)
}

func (m *NewModels) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetModels() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, NewModelsValidationError{
						field:  fmt.Sprintf("Models[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, NewModelsValidationError{
						field:  fmt.Sprintf("Models[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return NewModelsValidationError{
					field:  fmt.Sprintf("Models[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for TotalCount

	if len(errors) > 0 {
		return NewModelsMultiError(errors)
	}

	return nil
}

// NewModelsMultiError is an error wrapping multiple validation errors returned
// by NewModels.ValidateAll() if the designated constraints aren't met.
type NewModelsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NewModelsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NewModelsMultiError) AllErrors() []error { return m }

// NewModelsValidationError is the validation error returned by
// NewModels.Validate if the designated constraints aren't met.
type NewModelsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NewModelsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NewModelsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NewModelsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NewModelsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NewModelsValidationError) ErrorName() string { return "NewModelsValidationError" }

// Error satisfies the builtin error interface
func (e NewModelsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNewModels.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NewModelsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NewModelsValidationError{}

// Validate checks the field values on SyncStatus with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *SyncStatus) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SyncStatus with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in SyncStatusMultiError, or
// nil if none found.
func (m *SyncStatus) ValidateAll() error {
	return m.validate(true)
}

func (m *SyncStatus) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Success

	// no validation rules for Message

	// no validation rules for Version

	// no validation rules for NewModelsCount

	// no validation rules for NewProvidersCount

	if len(errors) > 0 {
		return SyncStatusMultiError(errors)
	}

	return nil
}

// SyncStatusMultiError is an error wrapping multiple validation errors
// returned by SyncStatus.ValidateAll() if the designated constraints aren't met.
type SyncStatusMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SyncStatusMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SyncStatusMultiError) AllErrors() []error { return m }

// SyncStatusValidationError is the validation error returned by
// SyncStatus.Validate if the designated constraints aren't met.
type SyncStatusValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SyncStatusValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SyncStatusValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SyncStatusValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SyncStatusValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SyncStatusValidationError) ErrorName() string { return "SyncStatusValidationError" }

// Error satisfies the builtin error interface
func (e SyncStatusValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSyncStatus.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SyncStatusValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SyncStatusValidationError{}
