// @generated by protoc-gen-es v2.2.0 with parameter "target=dts,json_types=true,import_extension=js"
// @generated from file everstack/scores/v1/service.proto (package everstack.scores.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import type { JsonObject, Message } from "@bufbuild/protobuf";
import type { StructJson, Timestamp, TimestampJson } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file everstack/scores/v1/service.proto.
 */
export declare const file_everstack_scores_v1_service: GenFile;

/**
 * @generated from message everstack.scores.v1.SubmitScoreRequest
 */
export declare type SubmitScoreRequest = Message<"everstack.scores.v1.SubmitScoreRequest"> & {
  /**
   * Required: Trace ID this score belongs to
   *
   * @generated from field: string trace_id = 1;
   */
  traceId: string;

  /**
   * Optional: Specific span/observation ID within the trace
   *
   * @generated from field: string observation_id = 2;
   */
  observationId: string;

  /**
   * Required: Score name (e.g., "quality", "accuracy", "coherence")
   *
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * Required: Score data type
   *
   * @generated from field: everstack.scores.v1.ScoreDataType data_type = 4;
   */
  dataType: ScoreDataType;

  /**
   * Score values (only one should be set based on data_type)
   *
   * @generated from field: optional double numeric_value = 5;
   */
  numericValue?: number;

  /**
   * @generated from field: optional string string_value = 6;
   */
  stringValue?: string;

  /**
   * @generated from field: optional bool boolean_value = 7;
   */
  booleanValue?: boolean;

  /**
   * Optional: How this score was created
   *
   * @generated from field: everstack.scores.v1.ScoreSource source = 8;
   */
  source: ScoreSource;

  /**
   * Optional: Human-readable comment
   *
   * @generated from field: string comment = 9;
   */
  comment: string;

  /**
   * Optional: User who created the score
   *
   * @generated from field: string author_user_id = 10;
   */
  authorUserId: string;

  /**
   * Optional: Additional metadata
   *
   * @generated from field: google.protobuf.Struct metadata = 11;
   */
  metadata?: JsonObject;

  /**
   * Optional: Reference to score config
   *
   * @generated from field: string config_id = 12;
   */
  configId: string;

  /**
   * Optional: Reference to annotation queue
   *
   * @generated from field: string queue_id = 13;
   */
  queueId: string;

  /**
   * Optional: Environment identifier
   *
   * @generated from field: string environment = 14;
   */
  environment: string;
};

/**
 * @generated from message everstack.scores.v1.SubmitScoreRequest
 */
export declare type SubmitScoreRequestJson = {
  /**
   * Required: Trace ID this score belongs to
   *
   * @generated from field: string trace_id = 1;
   */
  traceId?: string;

  /**
   * Optional: Specific span/observation ID within the trace
   *
   * @generated from field: string observation_id = 2;
   */
  observationId?: string;

  /**
   * Required: Score name (e.g., "quality", "accuracy", "coherence")
   *
   * @generated from field: string name = 3;
   */
  name?: string;

  /**
   * Required: Score data type
   *
   * @generated from field: everstack.scores.v1.ScoreDataType data_type = 4;
   */
  dataType?: ScoreDataTypeJson;

  /**
   * Score values (only one should be set based on data_type)
   *
   * @generated from field: optional double numeric_value = 5;
   */
  numericValue?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * @generated from field: optional string string_value = 6;
   */
  stringValue?: string;

  /**
   * @generated from field: optional bool boolean_value = 7;
   */
  booleanValue?: boolean;

  /**
   * Optional: How this score was created
   *
   * @generated from field: everstack.scores.v1.ScoreSource source = 8;
   */
  source?: ScoreSourceJson;

  /**
   * Optional: Human-readable comment
   *
   * @generated from field: string comment = 9;
   */
  comment?: string;

  /**
   * Optional: User who created the score
   *
   * @generated from field: string author_user_id = 10;
   */
  authorUserId?: string;

  /**
   * Optional: Additional metadata
   *
   * @generated from field: google.protobuf.Struct metadata = 11;
   */
  metadata?: StructJson;

  /**
   * Optional: Reference to score config
   *
   * @generated from field: string config_id = 12;
   */
  configId?: string;

  /**
   * Optional: Reference to annotation queue
   *
   * @generated from field: string queue_id = 13;
   */
  queueId?: string;

  /**
   * Optional: Environment identifier
   *
   * @generated from field: string environment = 14;
   */
  environment?: string;
};

/**
 * Describes the message everstack.scores.v1.SubmitScoreRequest.
 * Use `create(SubmitScoreRequestSchema)` to create a new message.
 */
export declare const SubmitScoreRequestSchema: GenMessage<SubmitScoreRequest, SubmitScoreRequestJson>;

/**
 * @generated from message everstack.scores.v1.SubmitScoreResponse
 */
export declare type SubmitScoreResponse = Message<"everstack.scores.v1.SubmitScoreResponse"> & {
  /**
   * Generated score ID
   *
   * @generated from field: string score_id = 1;
   */
  scoreId: string;

  /**
   * Whether the score was successfully recorded
   *
   * @generated from field: bool success = 2;
   */
  success: boolean;

  /**
   * Error message if success = false
   *
   * @generated from field: string error = 3;
   */
  error: string;
};

/**
 * @generated from message everstack.scores.v1.SubmitScoreResponse
 */
export declare type SubmitScoreResponseJson = {
  /**
   * Generated score ID
   *
   * @generated from field: string score_id = 1;
   */
  scoreId?: string;

  /**
   * Whether the score was successfully recorded
   *
   * @generated from field: bool success = 2;
   */
  success?: boolean;

  /**
   * Error message if success = false
   *
   * @generated from field: string error = 3;
   */
  error?: string;
};

/**
 * Describes the message everstack.scores.v1.SubmitScoreResponse.
 * Use `create(SubmitScoreResponseSchema)` to create a new message.
 */
export declare const SubmitScoreResponseSchema: GenMessage<SubmitScoreResponse, SubmitScoreResponseJson>;

/**
 * @generated from message everstack.scores.v1.SubmitScoreBatchRequest
 */
export declare type SubmitScoreBatchRequest = Message<"everstack.scores.v1.SubmitScoreBatchRequest"> & {
  /**
   * @generated from field: repeated everstack.scores.v1.SubmitScoreRequest scores = 1;
   */
  scores: SubmitScoreRequest[];
};

/**
 * @generated from message everstack.scores.v1.SubmitScoreBatchRequest
 */
export declare type SubmitScoreBatchRequestJson = {
  /**
   * @generated from field: repeated everstack.scores.v1.SubmitScoreRequest scores = 1;
   */
  scores?: SubmitScoreRequestJson[];
};

/**
 * Describes the message everstack.scores.v1.SubmitScoreBatchRequest.
 * Use `create(SubmitScoreBatchRequestSchema)` to create a new message.
 */
export declare const SubmitScoreBatchRequestSchema: GenMessage<SubmitScoreBatchRequest, SubmitScoreBatchRequestJson>;

/**
 * @generated from message everstack.scores.v1.SubmitScoreBatchResponse
 */
export declare type SubmitScoreBatchResponse = Message<"everstack.scores.v1.SubmitScoreBatchResponse"> & {
  /**
   * Number of scores successfully recorded
   *
   * @generated from field: int32 success_count = 1;
   */
  successCount: number;

  /**
   * Number of scores that failed
   *
   * @generated from field: int32 failure_count = 2;
   */
  failureCount: number;

  /**
   * Individual results for each score
   *
   * @generated from field: repeated everstack.scores.v1.SubmitScoreResponse results = 3;
   */
  results: SubmitScoreResponse[];
};

/**
 * @generated from message everstack.scores.v1.SubmitScoreBatchResponse
 */
export declare type SubmitScoreBatchResponseJson = {
  /**
   * Number of scores successfully recorded
   *
   * @generated from field: int32 success_count = 1;
   */
  successCount?: number;

  /**
   * Number of scores that failed
   *
   * @generated from field: int32 failure_count = 2;
   */
  failureCount?: number;

  /**
   * Individual results for each score
   *
   * @generated from field: repeated everstack.scores.v1.SubmitScoreResponse results = 3;
   */
  results?: SubmitScoreResponseJson[];
};

/**
 * Describes the message everstack.scores.v1.SubmitScoreBatchResponse.
 * Use `create(SubmitScoreBatchResponseSchema)` to create a new message.
 */
export declare const SubmitScoreBatchResponseSchema: GenMessage<SubmitScoreBatchResponse, SubmitScoreBatchResponseJson>;

/**
 * @generated from message everstack.scores.v1.GetScoresByTraceRequest
 */
export declare type GetScoresByTraceRequest = Message<"everstack.scores.v1.GetScoresByTraceRequest"> & {
  /**
   * @generated from field: string trace_id = 1;
   */
  traceId: string;
};

/**
 * @generated from message everstack.scores.v1.GetScoresByTraceRequest
 */
export declare type GetScoresByTraceRequestJson = {
  /**
   * @generated from field: string trace_id = 1;
   */
  traceId?: string;
};

/**
 * Describes the message everstack.scores.v1.GetScoresByTraceRequest.
 * Use `create(GetScoresByTraceRequestSchema)` to create a new message.
 */
export declare const GetScoresByTraceRequestSchema: GenMessage<GetScoresByTraceRequest, GetScoresByTraceRequestJson>;

/**
 * @generated from message everstack.scores.v1.GetScoresByTraceResponse
 */
export declare type GetScoresByTraceResponse = Message<"everstack.scores.v1.GetScoresByTraceResponse"> & {
  /**
   * @generated from field: repeated everstack.scores.v1.Score scores = 1;
   */
  scores: Score[];
};

/**
 * @generated from message everstack.scores.v1.GetScoresByTraceResponse
 */
export declare type GetScoresByTraceResponseJson = {
  /**
   * @generated from field: repeated everstack.scores.v1.Score scores = 1;
   */
  scores?: ScoreJson[];
};

/**
 * Describes the message everstack.scores.v1.GetScoresByTraceResponse.
 * Use `create(GetScoresByTraceResponseSchema)` to create a new message.
 */
export declare const GetScoresByTraceResponseSchema: GenMessage<GetScoresByTraceResponse, GetScoresByTraceResponseJson>;

/**
 * @generated from message everstack.scores.v1.Score
 */
export declare type Score = Message<"everstack.scores.v1.Score"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string trace_id = 2;
   */
  traceId: string;

  /**
   * @generated from field: string observation_id = 3;
   */
  observationId: string;

  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 4;
   */
  timestamp?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 5;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 6;
   */
  updatedAt?: Timestamp;

  /**
   * @generated from field: string name = 7;
   */
  name: string;

  /**
   * @generated from field: everstack.scores.v1.ScoreSource source = 8;
   */
  source: ScoreSource;

  /**
   * @generated from field: everstack.scores.v1.ScoreDataType data_type = 9;
   */
  dataType: ScoreDataType;

  /**
   * Score values
   *
   * @generated from field: optional double numeric_value = 10;
   */
  numericValue?: number;

  /**
   * @generated from field: optional string string_value = 11;
   */
  stringValue?: string;

  /**
   * @generated from field: optional bool boolean_value = 12;
   */
  booleanValue?: boolean;

  /**
   * @generated from field: string comment = 13;
   */
  comment: string;

  /**
   * @generated from field: string author_user_id = 14;
   */
  authorUserId: string;

  /**
   * @generated from field: string config_id = 15;
   */
  configId: string;

  /**
   * @generated from field: string queue_id = 16;
   */
  queueId: string;

  /**
   * @generated from field: google.protobuf.Struct metadata = 17;
   */
  metadata?: JsonObject;

  /**
   * @generated from field: string environment = 18;
   */
  environment: string;
};

/**
 * @generated from message everstack.scores.v1.Score
 */
export declare type ScoreJson = {
  /**
   * @generated from field: string id = 1;
   */
  id?: string;

  /**
   * @generated from field: string trace_id = 2;
   */
  traceId?: string;

  /**
   * @generated from field: string observation_id = 3;
   */
  observationId?: string;

  /**
   * @generated from field: google.protobuf.Timestamp timestamp = 4;
   */
  timestamp?: TimestampJson;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 5;
   */
  createdAt?: TimestampJson;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 6;
   */
  updatedAt?: TimestampJson;

  /**
   * @generated from field: string name = 7;
   */
  name?: string;

  /**
   * @generated from field: everstack.scores.v1.ScoreSource source = 8;
   */
  source?: ScoreSourceJson;

  /**
   * @generated from field: everstack.scores.v1.ScoreDataType data_type = 9;
   */
  dataType?: ScoreDataTypeJson;

  /**
   * Score values
   *
   * @generated from field: optional double numeric_value = 10;
   */
  numericValue?: number | "NaN" | "Infinity" | "-Infinity";

  /**
   * @generated from field: optional string string_value = 11;
   */
  stringValue?: string;

  /**
   * @generated from field: optional bool boolean_value = 12;
   */
  booleanValue?: boolean;

  /**
   * @generated from field: string comment = 13;
   */
  comment?: string;

  /**
   * @generated from field: string author_user_id = 14;
   */
  authorUserId?: string;

  /**
   * @generated from field: string config_id = 15;
   */
  configId?: string;

  /**
   * @generated from field: string queue_id = 16;
   */
  queueId?: string;

  /**
   * @generated from field: google.protobuf.Struct metadata = 17;
   */
  metadata?: StructJson;

  /**
   * @generated from field: string environment = 18;
   */
  environment?: string;
};

/**
 * Describes the message everstack.scores.v1.Score.
 * Use `create(ScoreSchema)` to create a new message.
 */
export declare const ScoreSchema: GenMessage<Score, ScoreJson>;

/**
 * @generated from enum everstack.scores.v1.ScoreDataType
 */
export enum ScoreDataType {
  /**
   * @generated from enum value: SCORE_DATA_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: SCORE_DATA_TYPE_NUMERIC = 1;
   */
  NUMERIC = 1,

  /**
   * @generated from enum value: SCORE_DATA_TYPE_CATEGORICAL = 2;
   */
  CATEGORICAL = 2,

  /**
   * @generated from enum value: SCORE_DATA_TYPE_BOOLEAN = 3;
   */
  BOOLEAN = 3,
}

/**
 * @generated from enum everstack.scores.v1.ScoreDataType
 */
export declare type ScoreDataTypeJson = "SCORE_DATA_TYPE_UNSPECIFIED" | "SCORE_DATA_TYPE_NUMERIC" | "SCORE_DATA_TYPE_CATEGORICAL" | "SCORE_DATA_TYPE_BOOLEAN";

/**
 * Describes the enum everstack.scores.v1.ScoreDataType.
 */
export declare const ScoreDataTypeSchema: GenEnum<ScoreDataType, ScoreDataTypeJson>;

/**
 * @generated from enum everstack.scores.v1.ScoreSource
 */
export enum ScoreSource {
  /**
   * @generated from enum value: SCORE_SOURCE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Manual annotation by human
   *
   * @generated from enum value: SCORE_SOURCE_ANNOTATION = 1;
   */
  ANNOTATION = 1,

  /**
   * Submitted via API
   *
   * @generated from enum value: SCORE_SOURCE_API = 2;
   */
  API = 2,

  /**
   * Generated by automated evaluation
   *
   * @generated from enum value: SCORE_SOURCE_EVAL = 3;
   */
  EVAL = 3,
}

/**
 * @generated from enum everstack.scores.v1.ScoreSource
 */
export declare type ScoreSourceJson = "SCORE_SOURCE_UNSPECIFIED" | "SCORE_SOURCE_ANNOTATION" | "SCORE_SOURCE_API" | "SCORE_SOURCE_EVAL";

/**
 * Describes the enum everstack.scores.v1.ScoreSource.
 */
export declare const ScoreSourceSchema: GenEnum<ScoreSource, ScoreSourceJson>;

/**
 * ScoreService provides APIs for submitting and querying evaluation scores
 *
 * @generated from service everstack.scores.v1.ScoreService
 */
export declare const ScoreService: GenService<{
  /**
   * SubmitScore adds a new evaluation score to a trace or observation
   *
   * @generated from rpc everstack.scores.v1.ScoreService.SubmitScore
   */
  submitScore: {
    methodKind: "unary";
    input: typeof SubmitScoreRequestSchema;
    output: typeof SubmitScoreResponseSchema;
  },
  /**
   * SubmitScoreBatch adds multiple scores in a single request
   *
   * @generated from rpc everstack.scores.v1.ScoreService.SubmitScoreBatch
   */
  submitScoreBatch: {
    methodKind: "unary";
    input: typeof SubmitScoreBatchRequestSchema;
    output: typeof SubmitScoreBatchResponseSchema;
  },
  /**
   * GetScoresByTrace retrieves all scores for a specific trace
   *
   * @generated from rpc everstack.scores.v1.ScoreService.GetScoresByTrace
   */
  getScoresByTrace: {
    methodKind: "unary";
    input: typeof GetScoresByTraceRequestSchema;
    output: typeof GetScoresByTraceResponseSchema;
  },
}>;

