// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: everstack/workflows/v1/workflows_service.proto

package workflows

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkflowsService_CreateWorkflow_FullMethodName            = "/everstack.workflows.v1.WorkflowsService/CreateWorkflow"
	WorkflowsService_GetWorkflow_FullMethodName               = "/everstack.workflows.v1.WorkflowsService/GetWorkflow"
	WorkflowsService_ListWorkflows_FullMethodName             = "/everstack.workflows.v1.WorkflowsService/ListWorkflows"
	WorkflowsService_UpdateWorkflow_FullMethodName            = "/everstack.workflows.v1.WorkflowsService/UpdateWorkflow"
	WorkflowsService_DeleteWorkflow_FullMethodName            = "/everstack.workflows.v1.WorkflowsService/DeleteWorkflow"
	WorkflowsService_ExecuteWorkflow_FullMethodName           = "/everstack.workflows.v1.WorkflowsService/ExecuteWorkflow"
	WorkflowsService_GetWorkflowVersionHistory_FullMethodName = "/everstack.workflows.v1.WorkflowsService/GetWorkflowVersionHistory"
	WorkflowsService_GetWorkflowAtVersion_FullMethodName      = "/everstack.workflows.v1.WorkflowsService/GetWorkflowAtVersion"
	WorkflowsService_SaveWorkflowDraft_FullMethodName         = "/everstack.workflows.v1.WorkflowsService/SaveWorkflowDraft"
	WorkflowsService_PublishWorkflow_FullMethodName           = "/everstack.workflows.v1.WorkflowsService/PublishWorkflow"
	WorkflowsService_UnpublishWorkflow_FullMethodName         = "/everstack.workflows.v1.WorkflowsService/UnpublishWorkflow"
	WorkflowsService_ListWorkflowExecutions_FullMethodName    = "/everstack.workflows.v1.WorkflowsService/ListWorkflowExecutions"
	WorkflowsService_GetWorkflowExecution_FullMethodName      = "/everstack.workflows.v1.WorkflowsService/GetWorkflowExecution"
	WorkflowsService_ReplayWorkflowExecution_FullMethodName   = "/everstack.workflows.v1.WorkflowsService/ReplayWorkflowExecution"
)

// WorkflowsServiceClient is the client API for WorkflowsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkflowsServiceClient interface {
	CreateWorkflow(ctx context.Context, in *CreateWorkflowRequest, opts ...grpc.CallOption) (*CreateWorkflowResponse, error)
	GetWorkflow(ctx context.Context, in *GetWorkflowRequest, opts ...grpc.CallOption) (*GetWorkflowResponse, error)
	ListWorkflows(ctx context.Context, in *ListWorkflowsRequest, opts ...grpc.CallOption) (*ListWorkflowsResponse, error)
	UpdateWorkflow(ctx context.Context, in *UpdateWorkflowRequest, opts ...grpc.CallOption) (*UpdateWorkflowResponse, error)
	DeleteWorkflow(ctx context.Context, in *DeleteWorkflowRequest, opts ...grpc.CallOption) (*DeleteWorkflowResponse, error)
	// Execute a workflow with streaming events
	ExecuteWorkflow(ctx context.Context, in *ExecuteWorkflowRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteWorkflowEvent], error)
	// Get version history for a workflow
	GetWorkflowVersionHistory(ctx context.Context, in *GetWorkflowVersionHistoryRequest, opts ...grpc.CallOption) (*GetWorkflowVersionHistoryResponse, error)
	// Get reconstructed workflow state at a specific version
	GetWorkflowAtVersion(ctx context.Context, in *GetWorkflowAtVersionRequest, opts ...grpc.CallOption) (*GetWorkflowAtVersionResponse, error)
	// Save workflow draft without creating a version event
	SaveWorkflowDraft(ctx context.Context, in *SaveWorkflowDraftRequest, opts ...grpc.CallOption) (*SaveWorkflowDraftResponse, error)
	// Publish workflow, creating a version snapshot
	PublishWorkflow(ctx context.Context, in *PublishWorkflowRequest, opts ...grpc.CallOption) (*PublishWorkflowResponse, error)
	// Unpublish workflow (move back to draft)
	UnpublishWorkflow(ctx context.Context, in *UnpublishWorkflowRequest, opts ...grpc.CallOption) (*UnpublishWorkflowResponse, error)
	// List execution history for a workflow
	ListWorkflowExecutions(ctx context.Context, in *ListWorkflowExecutionsRequest, opts ...grpc.CallOption) (*ListWorkflowExecutionsResponse, error)
	// Get a single workflow execution by ID
	GetWorkflowExecution(ctx context.Context, in *GetWorkflowExecutionRequest, opts ...grpc.CallOption) (*GetWorkflowExecutionResponse, error)
	// Replay a past workflow execution with the same inputs
	ReplayWorkflowExecution(ctx context.Context, in *ReplayWorkflowExecutionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteWorkflowEvent], error)
}

type workflowsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkflowsServiceClient(cc grpc.ClientConnInterface) WorkflowsServiceClient {
	return &workflowsServiceClient{cc}
}

func (c *workflowsServiceClient) CreateWorkflow(ctx context.Context, in *CreateWorkflowRequest, opts ...grpc.CallOption) (*CreateWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWorkflowResponse)
	err := c.cc.Invoke(ctx, WorkflowsService_CreateWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowsServiceClient) GetWorkflow(ctx context.Context, in *GetWorkflowRequest, opts ...grpc.CallOption) (*GetWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorkflowResponse)
	err := c.cc.Invoke(ctx, WorkflowsService_GetWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowsServiceClient) ListWorkflows(ctx context.Context, in *ListWorkflowsRequest, opts ...grpc.CallOption) (*ListWorkflowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkflowsResponse)
	err := c.cc.Invoke(ctx, WorkflowsService_ListWorkflows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowsServiceClient) UpdateWorkflow(ctx context.Context, in *UpdateWorkflowRequest, opts ...grpc.CallOption) (*UpdateWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateWorkflowResponse)
	err := c.cc.Invoke(ctx, WorkflowsService_UpdateWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowsServiceClient) DeleteWorkflow(ctx context.Context, in *DeleteWorkflowRequest, opts ...grpc.CallOption) (*DeleteWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteWorkflowResponse)
	err := c.cc.Invoke(ctx, WorkflowsService_DeleteWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowsServiceClient) ExecuteWorkflow(ctx context.Context, in *ExecuteWorkflowRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteWorkflowEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkflowsService_ServiceDesc.Streams[0], WorkflowsService_ExecuteWorkflow_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecuteWorkflowRequest, ExecuteWorkflowEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkflowsService_ExecuteWorkflowClient = grpc.ServerStreamingClient[ExecuteWorkflowEvent]

func (c *workflowsServiceClient) GetWorkflowVersionHistory(ctx context.Context, in *GetWorkflowVersionHistoryRequest, opts ...grpc.CallOption) (*GetWorkflowVersionHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorkflowVersionHistoryResponse)
	err := c.cc.Invoke(ctx, WorkflowsService_GetWorkflowVersionHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowsServiceClient) GetWorkflowAtVersion(ctx context.Context, in *GetWorkflowAtVersionRequest, opts ...grpc.CallOption) (*GetWorkflowAtVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorkflowAtVersionResponse)
	err := c.cc.Invoke(ctx, WorkflowsService_GetWorkflowAtVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowsServiceClient) SaveWorkflowDraft(ctx context.Context, in *SaveWorkflowDraftRequest, opts ...grpc.CallOption) (*SaveWorkflowDraftResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveWorkflowDraftResponse)
	err := c.cc.Invoke(ctx, WorkflowsService_SaveWorkflowDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowsServiceClient) PublishWorkflow(ctx context.Context, in *PublishWorkflowRequest, opts ...grpc.CallOption) (*PublishWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishWorkflowResponse)
	err := c.cc.Invoke(ctx, WorkflowsService_PublishWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowsServiceClient) UnpublishWorkflow(ctx context.Context, in *UnpublishWorkflowRequest, opts ...grpc.CallOption) (*UnpublishWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnpublishWorkflowResponse)
	err := c.cc.Invoke(ctx, WorkflowsService_UnpublishWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowsServiceClient) ListWorkflowExecutions(ctx context.Context, in *ListWorkflowExecutionsRequest, opts ...grpc.CallOption) (*ListWorkflowExecutionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWorkflowExecutionsResponse)
	err := c.cc.Invoke(ctx, WorkflowsService_ListWorkflowExecutions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowsServiceClient) GetWorkflowExecution(ctx context.Context, in *GetWorkflowExecutionRequest, opts ...grpc.CallOption) (*GetWorkflowExecutionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorkflowExecutionResponse)
	err := c.cc.Invoke(ctx, WorkflowsService_GetWorkflowExecution_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowsServiceClient) ReplayWorkflowExecution(ctx context.Context, in *ReplayWorkflowExecutionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ExecuteWorkflowEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkflowsService_ServiceDesc.Streams[1], WorkflowsService_ReplayWorkflowExecution_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReplayWorkflowExecutionRequest, ExecuteWorkflowEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkflowsService_ReplayWorkflowExecutionClient = grpc.ServerStreamingClient[ExecuteWorkflowEvent]

// WorkflowsServiceServer is the server API for WorkflowsService service.
// All implementations must embed UnimplementedWorkflowsServiceServer
// for forward compatibility.
type WorkflowsServiceServer interface {
	CreateWorkflow(context.Context, *CreateWorkflowRequest) (*CreateWorkflowResponse, error)
	GetWorkflow(context.Context, *GetWorkflowRequest) (*GetWorkflowResponse, error)
	ListWorkflows(context.Context, *ListWorkflowsRequest) (*ListWorkflowsResponse, error)
	UpdateWorkflow(context.Context, *UpdateWorkflowRequest) (*UpdateWorkflowResponse, error)
	DeleteWorkflow(context.Context, *DeleteWorkflowRequest) (*DeleteWorkflowResponse, error)
	// Execute a workflow with streaming events
	ExecuteWorkflow(*ExecuteWorkflowRequest, grpc.ServerStreamingServer[ExecuteWorkflowEvent]) error
	// Get version history for a workflow
	GetWorkflowVersionHistory(context.Context, *GetWorkflowVersionHistoryRequest) (*GetWorkflowVersionHistoryResponse, error)
	// Get reconstructed workflow state at a specific version
	GetWorkflowAtVersion(context.Context, *GetWorkflowAtVersionRequest) (*GetWorkflowAtVersionResponse, error)
	// Save workflow draft without creating a version event
	SaveWorkflowDraft(context.Context, *SaveWorkflowDraftRequest) (*SaveWorkflowDraftResponse, error)
	// Publish workflow, creating a version snapshot
	PublishWorkflow(context.Context, *PublishWorkflowRequest) (*PublishWorkflowResponse, error)
	// Unpublish workflow (move back to draft)
	UnpublishWorkflow(context.Context, *UnpublishWorkflowRequest) (*UnpublishWorkflowResponse, error)
	// List execution history for a workflow
	ListWorkflowExecutions(context.Context, *ListWorkflowExecutionsRequest) (*ListWorkflowExecutionsResponse, error)
	// Get a single workflow execution by ID
	GetWorkflowExecution(context.Context, *GetWorkflowExecutionRequest) (*GetWorkflowExecutionResponse, error)
	// Replay a past workflow execution with the same inputs
	ReplayWorkflowExecution(*ReplayWorkflowExecutionRequest, grpc.ServerStreamingServer[ExecuteWorkflowEvent]) error
	mustEmbedUnimplementedWorkflowsServiceServer()
}

// UnimplementedWorkflowsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkflowsServiceServer struct{}

func (UnimplementedWorkflowsServiceServer) CreateWorkflow(context.Context, *CreateWorkflowRequest) (*CreateWorkflowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWorkflow not implemented")
}
func (UnimplementedWorkflowsServiceServer) GetWorkflow(context.Context, *GetWorkflowRequest) (*GetWorkflowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkflow not implemented")
}
func (UnimplementedWorkflowsServiceServer) ListWorkflows(context.Context, *ListWorkflowsRequest) (*ListWorkflowsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorkflows not implemented")
}
func (UnimplementedWorkflowsServiceServer) UpdateWorkflow(context.Context, *UpdateWorkflowRequest) (*UpdateWorkflowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateWorkflow not implemented")
}
func (UnimplementedWorkflowsServiceServer) DeleteWorkflow(context.Context, *DeleteWorkflowRequest) (*DeleteWorkflowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteWorkflow not implemented")
}
func (UnimplementedWorkflowsServiceServer) ExecuteWorkflow(*ExecuteWorkflowRequest, grpc.ServerStreamingServer[ExecuteWorkflowEvent]) error {
	return status.Error(codes.Unimplemented, "method ExecuteWorkflow not implemented")
}
func (UnimplementedWorkflowsServiceServer) GetWorkflowVersionHistory(context.Context, *GetWorkflowVersionHistoryRequest) (*GetWorkflowVersionHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkflowVersionHistory not implemented")
}
func (UnimplementedWorkflowsServiceServer) GetWorkflowAtVersion(context.Context, *GetWorkflowAtVersionRequest) (*GetWorkflowAtVersionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkflowAtVersion not implemented")
}
func (UnimplementedWorkflowsServiceServer) SaveWorkflowDraft(context.Context, *SaveWorkflowDraftRequest) (*SaveWorkflowDraftResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveWorkflowDraft not implemented")
}
func (UnimplementedWorkflowsServiceServer) PublishWorkflow(context.Context, *PublishWorkflowRequest) (*PublishWorkflowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishWorkflow not implemented")
}
func (UnimplementedWorkflowsServiceServer) UnpublishWorkflow(context.Context, *UnpublishWorkflowRequest) (*UnpublishWorkflowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnpublishWorkflow not implemented")
}
func (UnimplementedWorkflowsServiceServer) ListWorkflowExecutions(context.Context, *ListWorkflowExecutionsRequest) (*ListWorkflowExecutionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWorkflowExecutions not implemented")
}
func (UnimplementedWorkflowsServiceServer) GetWorkflowExecution(context.Context, *GetWorkflowExecutionRequest) (*GetWorkflowExecutionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkflowExecution not implemented")
}
func (UnimplementedWorkflowsServiceServer) ReplayWorkflowExecution(*ReplayWorkflowExecutionRequest, grpc.ServerStreamingServer[ExecuteWorkflowEvent]) error {
	return status.Error(codes.Unimplemented, "method ReplayWorkflowExecution not implemented")
}
func (UnimplementedWorkflowsServiceServer) mustEmbedUnimplementedWorkflowsServiceServer() {}
func (UnimplementedWorkflowsServiceServer) testEmbeddedByValue()                          {}

// UnsafeWorkflowsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkflowsServiceServer will
// result in compilation errors.
type UnsafeWorkflowsServiceServer interface {
	mustEmbedUnimplementedWorkflowsServiceServer()
}

func RegisterWorkflowsServiceServer(s grpc.ServiceRegistrar, srv WorkflowsServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkflowsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkflowsService_ServiceDesc, srv)
}

func _WorkflowsService_CreateWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowsServiceServer).CreateWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowsService_CreateWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowsServiceServer).CreateWorkflow(ctx, req.(*CreateWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowsService_GetWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowsServiceServer).GetWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowsService_GetWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowsServiceServer).GetWorkflow(ctx, req.(*GetWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowsService_ListWorkflows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkflowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowsServiceServer).ListWorkflows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowsService_ListWorkflows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowsServiceServer).ListWorkflows(ctx, req.(*ListWorkflowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowsService_UpdateWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowsServiceServer).UpdateWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowsService_UpdateWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowsServiceServer).UpdateWorkflow(ctx, req.(*UpdateWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowsService_DeleteWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowsServiceServer).DeleteWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowsService_DeleteWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowsServiceServer).DeleteWorkflow(ctx, req.(*DeleteWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowsService_ExecuteWorkflow_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteWorkflowRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkflowsServiceServer).ExecuteWorkflow(m, &grpc.GenericServerStream[ExecuteWorkflowRequest, ExecuteWorkflowEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkflowsService_ExecuteWorkflowServer = grpc.ServerStreamingServer[ExecuteWorkflowEvent]

func _WorkflowsService_GetWorkflowVersionHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkflowVersionHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowsServiceServer).GetWorkflowVersionHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowsService_GetWorkflowVersionHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowsServiceServer).GetWorkflowVersionHistory(ctx, req.(*GetWorkflowVersionHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowsService_GetWorkflowAtVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkflowAtVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowsServiceServer).GetWorkflowAtVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowsService_GetWorkflowAtVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowsServiceServer).GetWorkflowAtVersion(ctx, req.(*GetWorkflowAtVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowsService_SaveWorkflowDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveWorkflowDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowsServiceServer).SaveWorkflowDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowsService_SaveWorkflowDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowsServiceServer).SaveWorkflowDraft(ctx, req.(*SaveWorkflowDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowsService_PublishWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowsServiceServer).PublishWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowsService_PublishWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowsServiceServer).PublishWorkflow(ctx, req.(*PublishWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowsService_UnpublishWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnpublishWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowsServiceServer).UnpublishWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowsService_UnpublishWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowsServiceServer).UnpublishWorkflow(ctx, req.(*UnpublishWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowsService_ListWorkflowExecutions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWorkflowExecutionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowsServiceServer).ListWorkflowExecutions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowsService_ListWorkflowExecutions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowsServiceServer).ListWorkflowExecutions(ctx, req.(*ListWorkflowExecutionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowsService_GetWorkflowExecution_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkflowExecutionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowsServiceServer).GetWorkflowExecution(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowsService_GetWorkflowExecution_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowsServiceServer).GetWorkflowExecution(ctx, req.(*GetWorkflowExecutionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowsService_ReplayWorkflowExecution_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReplayWorkflowExecutionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkflowsServiceServer).ReplayWorkflowExecution(m, &grpc.GenericServerStream[ReplayWorkflowExecutionRequest, ExecuteWorkflowEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkflowsService_ReplayWorkflowExecutionServer = grpc.ServerStreamingServer[ExecuteWorkflowEvent]

// WorkflowsService_ServiceDesc is the grpc.ServiceDesc for WorkflowsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkflowsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "everstack.workflows.v1.WorkflowsService",
	HandlerType: (*WorkflowsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWorkflow",
			Handler:    _WorkflowsService_CreateWorkflow_Handler,
		},
		{
			MethodName: "GetWorkflow",
			Handler:    _WorkflowsService_GetWorkflow_Handler,
		},
		{
			MethodName: "ListWorkflows",
			Handler:    _WorkflowsService_ListWorkflows_Handler,
		},
		{
			MethodName: "UpdateWorkflow",
			Handler:    _WorkflowsService_UpdateWorkflow_Handler,
		},
		{
			MethodName: "DeleteWorkflow",
			Handler:    _WorkflowsService_DeleteWorkflow_Handler,
		},
		{
			MethodName: "GetWorkflowVersionHistory",
			Handler:    _WorkflowsService_GetWorkflowVersionHistory_Handler,
		},
		{
			MethodName: "GetWorkflowAtVersion",
			Handler:    _WorkflowsService_GetWorkflowAtVersion_Handler,
		},
		{
			MethodName: "SaveWorkflowDraft",
			Handler:    _WorkflowsService_SaveWorkflowDraft_Handler,
		},
		{
			MethodName: "PublishWorkflow",
			Handler:    _WorkflowsService_PublishWorkflow_Handler,
		},
		{
			MethodName: "UnpublishWorkflow",
			Handler:    _WorkflowsService_UnpublishWorkflow_Handler,
		},
		{
			MethodName: "ListWorkflowExecutions",
			Handler:    _WorkflowsService_ListWorkflowExecutions_Handler,
		},
		{
			MethodName: "GetWorkflowExecution",
			Handler:    _WorkflowsService_GetWorkflowExecution_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteWorkflow",
			Handler:       _WorkflowsService_ExecuteWorkflow_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReplayWorkflowExecution",
			Handler:       _WorkflowsService_ReplayWorkflowExecution_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "everstack/workflows/v1/workflows_service.proto",
}
