// @generated by protoc-gen-es v2.2.0 with parameter "target=dts,json_types=true,import_extension=js"
// @generated from file everstack/api_key/v1/api_key_service.proto (package everstack.api_key.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv1";
import type { CreateApiKeyRequestSchema, CreateApiKeyResponseSchema, DeleteApiKeyRequestSchema, DeleteApiKeyResponseSchema, GetApiKeyRequestSchema, GetApiKeyResponseSchema, ListApiKeysRequestSchema, ListApiKeysResponseSchema, RegenerateApiKeyRequestSchema, RegenerateApiKeyResponseSchema, UpdateApiKeyRequestSchema, UpdateApiKeyResponseSchema } from "./api_key_pb.js";

/**
 * Describes the file everstack/api_key/v1/api_key_service.proto.
 */
export declare const file_everstack_api_key_v1_api_key_service: GenFile;

/**
 * @generated from service everstack.api_key.v1.ApiKeyService
 */
export declare const ApiKeyService: GenService<{
  /**
   * @generated from rpc everstack.api_key.v1.ApiKeyService.CreateApiKey
   */
  createApiKey: {
    methodKind: "unary";
    input: typeof CreateApiKeyRequestSchema;
    output: typeof CreateApiKeyResponseSchema;
  },
  /**
   * @generated from rpc everstack.api_key.v1.ApiKeyService.RegenerateApiKey
   */
  regenerateApiKey: {
    methodKind: "unary";
    input: typeof RegenerateApiKeyRequestSchema;
    output: typeof RegenerateApiKeyResponseSchema;
  },
  /**
   * @generated from rpc everstack.api_key.v1.ApiKeyService.UpdateApiKey
   */
  updateApiKey: {
    methodKind: "unary";
    input: typeof UpdateApiKeyRequestSchema;
    output: typeof UpdateApiKeyResponseSchema;
  },
  /**
   * @generated from rpc everstack.api_key.v1.ApiKeyService.DeleteApiKey
   */
  deleteApiKey: {
    methodKind: "unary";
    input: typeof DeleteApiKeyRequestSchema;
    output: typeof DeleteApiKeyResponseSchema;
  },
  /**
   * @generated from rpc everstack.api_key.v1.ApiKeyService.GetApiKey
   */
  getApiKey: {
    methodKind: "unary";
    input: typeof GetApiKeyRequestSchema;
    output: typeof GetApiKeyResponseSchema;
  },
  /**
   * @generated from rpc everstack.api_key.v1.ApiKeyService.ListApiKeys
   */
  listApiKeys: {
    methodKind: "unary";
    input: typeof ListApiKeysRequestSchema;
    output: typeof ListApiKeysResponseSchema;
  },
}>;

