// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: everstack/storage/v1/storage_service.proto

package storage

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ObjectStorageService_ConfigureStorage_FullMethodName        = "/everstack.storage.v1.ObjectStorageService/ConfigureStorage"
	ObjectStorageService_GetStorageConfig_FullMethodName        = "/everstack.storage.v1.ObjectStorageService/GetStorageConfig"
	ObjectStorageService_ListStorageConfigs_FullMethodName      = "/everstack.storage.v1.ObjectStorageService/ListStorageConfigs"
	ObjectStorageService_UpdateStorageConfig_FullMethodName     = "/everstack.storage.v1.ObjectStorageService/UpdateStorageConfig"
	ObjectStorageService_DeleteStorageConfig_FullMethodName     = "/everstack.storage.v1.ObjectStorageService/DeleteStorageConfig"
	ObjectStorageService_GetPresignedUploadURL_FullMethodName   = "/everstack.storage.v1.ObjectStorageService/GetPresignedUploadURL"
	ObjectStorageService_CompleteUpload_FullMethodName          = "/everstack.storage.v1.ObjectStorageService/CompleteUpload"
	ObjectStorageService_GetUploadStatus_FullMethodName         = "/everstack.storage.v1.ObjectStorageService/GetUploadStatus"
	ObjectStorageService_GetPresignedDownloadURL_FullMethodName = "/everstack.storage.v1.ObjectStorageService/GetPresignedDownloadURL"
	ObjectStorageService_DeleteObject_FullMethodName            = "/everstack.storage.v1.ObjectStorageService/DeleteObject"
	ObjectStorageService_ListObjects_FullMethodName             = "/everstack.storage.v1.ObjectStorageService/ListObjects"
	ObjectStorageService_GetStorageUsage_FullMethodName         = "/everstack.storage.v1.ObjectStorageService/GetStorageUsage"
)

// ObjectStorageServiceClient is the client API for ObjectStorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ObjectStorageServiceClient interface {
	ConfigureStorage(ctx context.Context, in *ConfigureStorageRequest, opts ...grpc.CallOption) (*ConfigureStorageResponse, error)
	GetStorageConfig(ctx context.Context, in *GetStorageConfigRequest, opts ...grpc.CallOption) (*GetStorageConfigResponse, error)
	ListStorageConfigs(ctx context.Context, in *ListStorageConfigsRequest, opts ...grpc.CallOption) (*ListStorageConfigsResponse, error)
	UpdateStorageConfig(ctx context.Context, in *UpdateStorageConfigRequest, opts ...grpc.CallOption) (*UpdateStorageConfigResponse, error)
	DeleteStorageConfig(ctx context.Context, in *DeleteStorageConfigRequest, opts ...grpc.CallOption) (*DeleteStorageConfigResponse, error)
	GetPresignedUploadURL(ctx context.Context, in *GetPresignedUploadURLRequest, opts ...grpc.CallOption) (*GetPresignedUploadURLResponse, error)
	CompleteUpload(ctx context.Context, in *CompleteUploadRequest, opts ...grpc.CallOption) (*CompleteUploadResponse, error)
	GetUploadStatus(ctx context.Context, in *GetUploadStatusRequest, opts ...grpc.CallOption) (*GetUploadStatusResponse, error)
	GetPresignedDownloadURL(ctx context.Context, in *GetPresignedDownloadURLRequest, opts ...grpc.CallOption) (*GetPresignedDownloadURLResponse, error)
	DeleteObject(ctx context.Context, in *DeleteObjectRequest, opts ...grpc.CallOption) (*DeleteObjectResponse, error)
	ListObjects(ctx context.Context, in *ListObjectsRequest, opts ...grpc.CallOption) (*ListObjectsResponse, error)
	GetStorageUsage(ctx context.Context, in *GetStorageUsageRequest, opts ...grpc.CallOption) (*GetStorageUsageResponse, error)
}

type objectStorageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewObjectStorageServiceClient(cc grpc.ClientConnInterface) ObjectStorageServiceClient {
	return &objectStorageServiceClient{cc}
}

func (c *objectStorageServiceClient) ConfigureStorage(ctx context.Context, in *ConfigureStorageRequest, opts ...grpc.CallOption) (*ConfigureStorageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfigureStorageResponse)
	err := c.cc.Invoke(ctx, ObjectStorageService_ConfigureStorage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectStorageServiceClient) GetStorageConfig(ctx context.Context, in *GetStorageConfigRequest, opts ...grpc.CallOption) (*GetStorageConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStorageConfigResponse)
	err := c.cc.Invoke(ctx, ObjectStorageService_GetStorageConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectStorageServiceClient) ListStorageConfigs(ctx context.Context, in *ListStorageConfigsRequest, opts ...grpc.CallOption) (*ListStorageConfigsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStorageConfigsResponse)
	err := c.cc.Invoke(ctx, ObjectStorageService_ListStorageConfigs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectStorageServiceClient) UpdateStorageConfig(ctx context.Context, in *UpdateStorageConfigRequest, opts ...grpc.CallOption) (*UpdateStorageConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateStorageConfigResponse)
	err := c.cc.Invoke(ctx, ObjectStorageService_UpdateStorageConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectStorageServiceClient) DeleteStorageConfig(ctx context.Context, in *DeleteStorageConfigRequest, opts ...grpc.CallOption) (*DeleteStorageConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteStorageConfigResponse)
	err := c.cc.Invoke(ctx, ObjectStorageService_DeleteStorageConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectStorageServiceClient) GetPresignedUploadURL(ctx context.Context, in *GetPresignedUploadURLRequest, opts ...grpc.CallOption) (*GetPresignedUploadURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPresignedUploadURLResponse)
	err := c.cc.Invoke(ctx, ObjectStorageService_GetPresignedUploadURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectStorageServiceClient) CompleteUpload(ctx context.Context, in *CompleteUploadRequest, opts ...grpc.CallOption) (*CompleteUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteUploadResponse)
	err := c.cc.Invoke(ctx, ObjectStorageService_CompleteUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectStorageServiceClient) GetUploadStatus(ctx context.Context, in *GetUploadStatusRequest, opts ...grpc.CallOption) (*GetUploadStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUploadStatusResponse)
	err := c.cc.Invoke(ctx, ObjectStorageService_GetUploadStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectStorageServiceClient) GetPresignedDownloadURL(ctx context.Context, in *GetPresignedDownloadURLRequest, opts ...grpc.CallOption) (*GetPresignedDownloadURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPresignedDownloadURLResponse)
	err := c.cc.Invoke(ctx, ObjectStorageService_GetPresignedDownloadURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectStorageServiceClient) DeleteObject(ctx context.Context, in *DeleteObjectRequest, opts ...grpc.CallOption) (*DeleteObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteObjectResponse)
	err := c.cc.Invoke(ctx, ObjectStorageService_DeleteObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectStorageServiceClient) ListObjects(ctx context.Context, in *ListObjectsRequest, opts ...grpc.CallOption) (*ListObjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListObjectsResponse)
	err := c.cc.Invoke(ctx, ObjectStorageService_ListObjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectStorageServiceClient) GetStorageUsage(ctx context.Context, in *GetStorageUsageRequest, opts ...grpc.CallOption) (*GetStorageUsageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStorageUsageResponse)
	err := c.cc.Invoke(ctx, ObjectStorageService_GetStorageUsage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ObjectStorageServiceServer is the server API for ObjectStorageService service.
// All implementations must embed UnimplementedObjectStorageServiceServer
// for forward compatibility.
type ObjectStorageServiceServer interface {
	ConfigureStorage(context.Context, *ConfigureStorageRequest) (*ConfigureStorageResponse, error)
	GetStorageConfig(context.Context, *GetStorageConfigRequest) (*GetStorageConfigResponse, error)
	ListStorageConfigs(context.Context, *ListStorageConfigsRequest) (*ListStorageConfigsResponse, error)
	UpdateStorageConfig(context.Context, *UpdateStorageConfigRequest) (*UpdateStorageConfigResponse, error)
	DeleteStorageConfig(context.Context, *DeleteStorageConfigRequest) (*DeleteStorageConfigResponse, error)
	GetPresignedUploadURL(context.Context, *GetPresignedUploadURLRequest) (*GetPresignedUploadURLResponse, error)
	CompleteUpload(context.Context, *CompleteUploadRequest) (*CompleteUploadResponse, error)
	GetUploadStatus(context.Context, *GetUploadStatusRequest) (*GetUploadStatusResponse, error)
	GetPresignedDownloadURL(context.Context, *GetPresignedDownloadURLRequest) (*GetPresignedDownloadURLResponse, error)
	DeleteObject(context.Context, *DeleteObjectRequest) (*DeleteObjectResponse, error)
	ListObjects(context.Context, *ListObjectsRequest) (*ListObjectsResponse, error)
	GetStorageUsage(context.Context, *GetStorageUsageRequest) (*GetStorageUsageResponse, error)
	mustEmbedUnimplementedObjectStorageServiceServer()
}

// UnimplementedObjectStorageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedObjectStorageServiceServer struct{}

func (UnimplementedObjectStorageServiceServer) ConfigureStorage(context.Context, *ConfigureStorageRequest) (*ConfigureStorageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigureStorage not implemented")
}
func (UnimplementedObjectStorageServiceServer) GetStorageConfig(context.Context, *GetStorageConfigRequest) (*GetStorageConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStorageConfig not implemented")
}
func (UnimplementedObjectStorageServiceServer) ListStorageConfigs(context.Context, *ListStorageConfigsRequest) (*ListStorageConfigsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStorageConfigs not implemented")
}
func (UnimplementedObjectStorageServiceServer) UpdateStorageConfig(context.Context, *UpdateStorageConfigRequest) (*UpdateStorageConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateStorageConfig not implemented")
}
func (UnimplementedObjectStorageServiceServer) DeleteStorageConfig(context.Context, *DeleteStorageConfigRequest) (*DeleteStorageConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteStorageConfig not implemented")
}
func (UnimplementedObjectStorageServiceServer) GetPresignedUploadURL(context.Context, *GetPresignedUploadURLRequest) (*GetPresignedUploadURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPresignedUploadURL not implemented")
}
func (UnimplementedObjectStorageServiceServer) CompleteUpload(context.Context, *CompleteUploadRequest) (*CompleteUploadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteUpload not implemented")
}
func (UnimplementedObjectStorageServiceServer) GetUploadStatus(context.Context, *GetUploadStatusRequest) (*GetUploadStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUploadStatus not implemented")
}
func (UnimplementedObjectStorageServiceServer) GetPresignedDownloadURL(context.Context, *GetPresignedDownloadURLRequest) (*GetPresignedDownloadURLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPresignedDownloadURL not implemented")
}
func (UnimplementedObjectStorageServiceServer) DeleteObject(context.Context, *DeleteObjectRequest) (*DeleteObjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteObject not implemented")
}
func (UnimplementedObjectStorageServiceServer) ListObjects(context.Context, *ListObjectsRequest) (*ListObjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListObjects not implemented")
}
func (UnimplementedObjectStorageServiceServer) GetStorageUsage(context.Context, *GetStorageUsageRequest) (*GetStorageUsageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStorageUsage not implemented")
}
func (UnimplementedObjectStorageServiceServer) mustEmbedUnimplementedObjectStorageServiceServer() {}
func (UnimplementedObjectStorageServiceServer) testEmbeddedByValue()                              {}

// UnsafeObjectStorageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ObjectStorageServiceServer will
// result in compilation errors.
type UnsafeObjectStorageServiceServer interface {
	mustEmbedUnimplementedObjectStorageServiceServer()
}

func RegisterObjectStorageServiceServer(s grpc.ServiceRegistrar, srv ObjectStorageServiceServer) {
	// If the following call panics, it indicates UnimplementedObjectStorageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ObjectStorageService_ServiceDesc, srv)
}

func _ObjectStorageService_ConfigureStorage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigureStorageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStorageServiceServer).ConfigureStorage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectStorageService_ConfigureStorage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStorageServiceServer).ConfigureStorage(ctx, req.(*ConfigureStorageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectStorageService_GetStorageConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStorageConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStorageServiceServer).GetStorageConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectStorageService_GetStorageConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStorageServiceServer).GetStorageConfig(ctx, req.(*GetStorageConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectStorageService_ListStorageConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStorageConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStorageServiceServer).ListStorageConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectStorageService_ListStorageConfigs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStorageServiceServer).ListStorageConfigs(ctx, req.(*ListStorageConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectStorageService_UpdateStorageConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStorageConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStorageServiceServer).UpdateStorageConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectStorageService_UpdateStorageConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStorageServiceServer).UpdateStorageConfig(ctx, req.(*UpdateStorageConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectStorageService_DeleteStorageConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStorageConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStorageServiceServer).DeleteStorageConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectStorageService_DeleteStorageConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStorageServiceServer).DeleteStorageConfig(ctx, req.(*DeleteStorageConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectStorageService_GetPresignedUploadURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPresignedUploadURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStorageServiceServer).GetPresignedUploadURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectStorageService_GetPresignedUploadURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStorageServiceServer).GetPresignedUploadURL(ctx, req.(*GetPresignedUploadURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectStorageService_CompleteUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStorageServiceServer).CompleteUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectStorageService_CompleteUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStorageServiceServer).CompleteUpload(ctx, req.(*CompleteUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectStorageService_GetUploadStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUploadStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStorageServiceServer).GetUploadStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectStorageService_GetUploadStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStorageServiceServer).GetUploadStatus(ctx, req.(*GetUploadStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectStorageService_GetPresignedDownloadURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPresignedDownloadURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStorageServiceServer).GetPresignedDownloadURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectStorageService_GetPresignedDownloadURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStorageServiceServer).GetPresignedDownloadURL(ctx, req.(*GetPresignedDownloadURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectStorageService_DeleteObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStorageServiceServer).DeleteObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectStorageService_DeleteObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStorageServiceServer).DeleteObject(ctx, req.(*DeleteObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectStorageService_ListObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListObjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStorageServiceServer).ListObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectStorageService_ListObjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStorageServiceServer).ListObjects(ctx, req.(*ListObjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectStorageService_GetStorageUsage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStorageUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectStorageServiceServer).GetStorageUsage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ObjectStorageService_GetStorageUsage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectStorageServiceServer).GetStorageUsage(ctx, req.(*GetStorageUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ObjectStorageService_ServiceDesc is the grpc.ServiceDesc for ObjectStorageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ObjectStorageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "everstack.storage.v1.ObjectStorageService",
	HandlerType: (*ObjectStorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConfigureStorage",
			Handler:    _ObjectStorageService_ConfigureStorage_Handler,
		},
		{
			MethodName: "GetStorageConfig",
			Handler:    _ObjectStorageService_GetStorageConfig_Handler,
		},
		{
			MethodName: "ListStorageConfigs",
			Handler:    _ObjectStorageService_ListStorageConfigs_Handler,
		},
		{
			MethodName: "UpdateStorageConfig",
			Handler:    _ObjectStorageService_UpdateStorageConfig_Handler,
		},
		{
			MethodName: "DeleteStorageConfig",
			Handler:    _ObjectStorageService_DeleteStorageConfig_Handler,
		},
		{
			MethodName: "GetPresignedUploadURL",
			Handler:    _ObjectStorageService_GetPresignedUploadURL_Handler,
		},
		{
			MethodName: "CompleteUpload",
			Handler:    _ObjectStorageService_CompleteUpload_Handler,
		},
		{
			MethodName: "GetUploadStatus",
			Handler:    _ObjectStorageService_GetUploadStatus_Handler,
		},
		{
			MethodName: "GetPresignedDownloadURL",
			Handler:    _ObjectStorageService_GetPresignedDownloadURL_Handler,
		},
		{
			MethodName: "DeleteObject",
			Handler:    _ObjectStorageService_DeleteObject_Handler,
		},
		{
			MethodName: "ListObjects",
			Handler:    _ObjectStorageService_ListObjects_Handler,
		},
		{
			MethodName: "GetStorageUsage",
			Handler:    _ObjectStorageService_GetStorageUsage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "everstack/storage/v1/storage_service.proto",
}
