// @generated by protoc-gen-es v2.2.0 with parameter "target=dts,json_types=true,import_extension=js"
// @generated from file everstack/onboarding/v1/onboarding_service.proto (package everstack.onboarding.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { OnboardingState, OnboardingStateJson } from "./onboarding_pb.js";

/**
 * Describes the file everstack/onboarding/v1/onboarding_service.proto.
 */
export declare const file_everstack_onboarding_v1_onboarding_service: GenFile;

/**
 * @generated from message everstack.onboarding.v1.GetOnboardingStateRequest
 */
export declare type GetOnboardingStateRequest = Message<"everstack.onboarding.v1.GetOnboardingStateRequest"> & {
};

/**
 * @generated from message everstack.onboarding.v1.GetOnboardingStateRequest
 */
export declare type GetOnboardingStateRequestJson = {
};

/**
 * Describes the message everstack.onboarding.v1.GetOnboardingStateRequest.
 * Use `create(GetOnboardingStateRequestSchema)` to create a new message.
 */
export declare const GetOnboardingStateRequestSchema: GenMessage<GetOnboardingStateRequest, GetOnboardingStateRequestJson>;

/**
 * @generated from message everstack.onboarding.v1.GetOnboardingStateResponse
 */
export declare type GetOnboardingStateResponse = Message<"everstack.onboarding.v1.GetOnboardingStateResponse"> & {
  /**
   * @generated from field: everstack.onboarding.v1.OnboardingState state = 1;
   */
  state?: OnboardingState;
};

/**
 * @generated from message everstack.onboarding.v1.GetOnboardingStateResponse
 */
export declare type GetOnboardingStateResponseJson = {
  /**
   * @generated from field: everstack.onboarding.v1.OnboardingState state = 1;
   */
  state?: OnboardingStateJson;
};

/**
 * Describes the message everstack.onboarding.v1.GetOnboardingStateResponse.
 * Use `create(GetOnboardingStateResponseSchema)` to create a new message.
 */
export declare const GetOnboardingStateResponseSchema: GenMessage<GetOnboardingStateResponse, GetOnboardingStateResponseJson>;

/**
 * @generated from message everstack.onboarding.v1.UpdateOnboardingStateRequest
 */
export declare type UpdateOnboardingStateRequest = Message<"everstack.onboarding.v1.UpdateOnboardingStateRequest"> & {
  /**
   * @generated from field: bool dismissed = 1;
   */
  dismissed: boolean;

  /**
   * @generated from field: bool celebration_shown = 2;
   */
  celebrationShown: boolean;

  /**
   * @generated from field: string selected_path = 3;
   */
  selectedPath: string;

  /**
   * @generated from field: bool sandbox_skipped = 4;
   */
  sandboxSkipped: boolean;
};

/**
 * @generated from message everstack.onboarding.v1.UpdateOnboardingStateRequest
 */
export declare type UpdateOnboardingStateRequestJson = {
  /**
   * @generated from field: bool dismissed = 1;
   */
  dismissed?: boolean;

  /**
   * @generated from field: bool celebration_shown = 2;
   */
  celebrationShown?: boolean;

  /**
   * @generated from field: string selected_path = 3;
   */
  selectedPath?: string;

  /**
   * @generated from field: bool sandbox_skipped = 4;
   */
  sandboxSkipped?: boolean;
};

/**
 * Describes the message everstack.onboarding.v1.UpdateOnboardingStateRequest.
 * Use `create(UpdateOnboardingStateRequestSchema)` to create a new message.
 */
export declare const UpdateOnboardingStateRequestSchema: GenMessage<UpdateOnboardingStateRequest, UpdateOnboardingStateRequestJson>;

/**
 * @generated from message everstack.onboarding.v1.UpdateOnboardingStateResponse
 */
export declare type UpdateOnboardingStateResponse = Message<"everstack.onboarding.v1.UpdateOnboardingStateResponse"> & {
  /**
   * @generated from field: everstack.onboarding.v1.OnboardingState state = 1;
   */
  state?: OnboardingState;
};

/**
 * @generated from message everstack.onboarding.v1.UpdateOnboardingStateResponse
 */
export declare type UpdateOnboardingStateResponseJson = {
  /**
   * @generated from field: everstack.onboarding.v1.OnboardingState state = 1;
   */
  state?: OnboardingStateJson;
};

/**
 * Describes the message everstack.onboarding.v1.UpdateOnboardingStateResponse.
 * Use `create(UpdateOnboardingStateResponseSchema)` to create a new message.
 */
export declare const UpdateOnboardingStateResponseSchema: GenMessage<UpdateOnboardingStateResponse, UpdateOnboardingStateResponseJson>;

/**
 * OnboardingService persists the tenant-scoped launch-center state so it
 * survives a cleared browser cache or a fresh device. Connect-only: the admin
 * SPA talks to it over ConnectRPC, so no grpc-gateway REST mapping is wired.
 *
 * @generated from service everstack.onboarding.v1.OnboardingService
 */
export declare const OnboardingService: GenService<{
  /**
   * GetOnboardingState returns the stored state for the caller's tenant, or a
   * zero-value state if nothing has been persisted yet.
   *
   * @generated from rpc everstack.onboarding.v1.OnboardingService.GetOnboardingState
   */
  getOnboardingState: {
    methodKind: "unary";
    input: typeof GetOnboardingStateRequestSchema;
    output: typeof GetOnboardingStateResponseSchema;
  },
  /**
   * UpdateOnboardingState upserts the full state for the caller's tenant. The
   * client always sends a complete snapshot, so this is a wholesale replace.
   *
   * @generated from rpc everstack.onboarding.v1.OnboardingService.UpdateOnboardingState
   */
  updateOnboardingState: {
    methodKind: "unary";
    input: typeof UpdateOnboardingStateRequestSchema;
    output: typeof UpdateOnboardingStateResponseSchema;
  },
}>;

