// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: everstack/gateway/v1/moderations.proto

package gateway

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ModerationInput with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ModerationInput) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ModerationInput with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ModerationInputMultiError, or nil if none found.
func (m *ModerationInput) ValidateAll() error {
	return m.validate(true)
}

func (m *ModerationInput) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Type

	// no validation rules for Text

	if all {
		switch v := interface{}(m.GetImageUrl()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ModerationInputValidationError{
					field:  "ImageUrl",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ModerationInputValidationError{
					field:  "ImageUrl",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetImageUrl()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ModerationInputValidationError{
				field:  "ImageUrl",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ModerationInputMultiError(errors)
	}

	return nil
}

// ModerationInputMultiError is an error wrapping multiple validation errors
// returned by ModerationInput.ValidateAll() if the designated constraints
// aren't met.
type ModerationInputMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ModerationInputMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ModerationInputMultiError) AllErrors() []error { return m }

// ModerationInputValidationError is the validation error returned by
// ModerationInput.Validate if the designated constraints aren't met.
type ModerationInputValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ModerationInputValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ModerationInputValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ModerationInputValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ModerationInputValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ModerationInputValidationError) ErrorName() string { return "ModerationInputValidationError" }

// Error satisfies the builtin error interface
func (e ModerationInputValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sModerationInput.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ModerationInputValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ModerationInputValidationError{}

// Validate checks the field values on ModerationImageUrl with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ModerationImageUrl) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ModerationImageUrl with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ModerationImageUrlMultiError, or nil if none found.
func (m *ModerationImageUrl) ValidateAll() error {
	return m.validate(true)
}

func (m *ModerationImageUrl) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Url

	if len(errors) > 0 {
		return ModerationImageUrlMultiError(errors)
	}

	return nil
}

// ModerationImageUrlMultiError is an error wrapping multiple validation errors
// returned by ModerationImageUrl.ValidateAll() if the designated constraints
// aren't met.
type ModerationImageUrlMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ModerationImageUrlMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ModerationImageUrlMultiError) AllErrors() []error { return m }

// ModerationImageUrlValidationError is the validation error returned by
// ModerationImageUrl.Validate if the designated constraints aren't met.
type ModerationImageUrlValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ModerationImageUrlValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ModerationImageUrlValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ModerationImageUrlValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ModerationImageUrlValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ModerationImageUrlValidationError) ErrorName() string {
	return "ModerationImageUrlValidationError"
}

// Error satisfies the builtin error interface
func (e ModerationImageUrlValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sModerationImageUrl.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ModerationImageUrlValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ModerationImageUrlValidationError{}

// Validate checks the field values on ModerationRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ModerationRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ModerationRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ModerationRequestMultiError, or nil if none found.
func (m *ModerationRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ModerationRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Input

	for idx, item := range m.GetInputs() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ModerationRequestValidationError{
						field:  fmt.Sprintf("Inputs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ModerationRequestValidationError{
						field:  fmt.Sprintf("Inputs[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ModerationRequestValidationError{
					field:  fmt.Sprintf("Inputs[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for Model

	if all {
		switch v := interface{}(m.GetMetadata()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ModerationRequestValidationError{
					field:  "Metadata",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ModerationRequestValidationError{
					field:  "Metadata",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMetadata()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ModerationRequestValidationError{
				field:  "Metadata",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ModerationRequestMultiError(errors)
	}

	return nil
}

// ModerationRequestMultiError is an error wrapping multiple validation errors
// returned by ModerationRequest.ValidateAll() if the designated constraints
// aren't met.
type ModerationRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ModerationRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ModerationRequestMultiError) AllErrors() []error { return m }

// ModerationRequestValidationError is the validation error returned by
// ModerationRequest.Validate if the designated constraints aren't met.
type ModerationRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ModerationRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ModerationRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ModerationRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ModerationRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ModerationRequestValidationError) ErrorName() string {
	return "ModerationRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ModerationRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sModerationRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ModerationRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ModerationRequestValidationError{}

// Validate checks the field values on ModerationCategories with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ModerationCategories) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ModerationCategories with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ModerationCategoriesMultiError, or nil if none found.
func (m *ModerationCategories) ValidateAll() error {
	return m.validate(true)
}

func (m *ModerationCategories) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Hate

	// no validation rules for HateThreatening

	// no validation rules for Harassment

	// no validation rules for HarassmentThreatening

	// no validation rules for Illicit

	// no validation rules for IllicitViolent

	// no validation rules for SelfHarm

	// no validation rules for SelfHarmIntent

	// no validation rules for SelfHarmInstructions

	// no validation rules for Sexual

	// no validation rules for SexualMinors

	// no validation rules for Violence

	// no validation rules for ViolenceGraphic

	if len(errors) > 0 {
		return ModerationCategoriesMultiError(errors)
	}

	return nil
}

// ModerationCategoriesMultiError is an error wrapping multiple validation
// errors returned by ModerationCategories.ValidateAll() if the designated
// constraints aren't met.
type ModerationCategoriesMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ModerationCategoriesMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ModerationCategoriesMultiError) AllErrors() []error { return m }

// ModerationCategoriesValidationError is the validation error returned by
// ModerationCategories.Validate if the designated constraints aren't met.
type ModerationCategoriesValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ModerationCategoriesValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ModerationCategoriesValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ModerationCategoriesValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ModerationCategoriesValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ModerationCategoriesValidationError) ErrorName() string {
	return "ModerationCategoriesValidationError"
}

// Error satisfies the builtin error interface
func (e ModerationCategoriesValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sModerationCategories.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ModerationCategoriesValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ModerationCategoriesValidationError{}

// Validate checks the field values on ModerationCategoryScores with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ModerationCategoryScores) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ModerationCategoryScores with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ModerationCategoryScoresMultiError, or nil if none found.
func (m *ModerationCategoryScores) ValidateAll() error {
	return m.validate(true)
}

func (m *ModerationCategoryScores) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Hate

	// no validation rules for HateThreatening

	// no validation rules for Harassment

	// no validation rules for HarassmentThreatening

	// no validation rules for Illicit

	// no validation rules for IllicitViolent

	// no validation rules for SelfHarm

	// no validation rules for SelfHarmIntent

	// no validation rules for SelfHarmInstructions

	// no validation rules for Sexual

	// no validation rules for SexualMinors

	// no validation rules for Violence

	// no validation rules for ViolenceGraphic

	if len(errors) > 0 {
		return ModerationCategoryScoresMultiError(errors)
	}

	return nil
}

// ModerationCategoryScoresMultiError is an error wrapping multiple validation
// errors returned by ModerationCategoryScores.ValidateAll() if the designated
// constraints aren't met.
type ModerationCategoryScoresMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ModerationCategoryScoresMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ModerationCategoryScoresMultiError) AllErrors() []error { return m }

// ModerationCategoryScoresValidationError is the validation error returned by
// ModerationCategoryScores.Validate if the designated constraints aren't met.
type ModerationCategoryScoresValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ModerationCategoryScoresValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ModerationCategoryScoresValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ModerationCategoryScoresValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ModerationCategoryScoresValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ModerationCategoryScoresValidationError) ErrorName() string {
	return "ModerationCategoryScoresValidationError"
}

// Error satisfies the builtin error interface
func (e ModerationCategoryScoresValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sModerationCategoryScores.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ModerationCategoryScoresValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ModerationCategoryScoresValidationError{}

// Validate checks the field values on ModerationCategoryAppliedInputTypes with
// the rules defined in the proto definition for this message. If any rules
// are violated, the first error encountered is returned, or nil if there are
// no violations.
func (m *ModerationCategoryAppliedInputTypes) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ModerationCategoryAppliedInputTypes
// with the rules defined in the proto definition for this message. If any
// rules are violated, the result is a list of violation errors wrapped in
// ModerationCategoryAppliedInputTypesMultiError, or nil if none found.
func (m *ModerationCategoryAppliedInputTypes) ValidateAll() error {
	return m.validate(true)
}

func (m *ModerationCategoryAppliedInputTypes) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ModerationCategoryAppliedInputTypesMultiError(errors)
	}

	return nil
}

// ModerationCategoryAppliedInputTypesMultiError is an error wrapping multiple
// validation errors returned by
// ModerationCategoryAppliedInputTypes.ValidateAll() if the designated
// constraints aren't met.
type ModerationCategoryAppliedInputTypesMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ModerationCategoryAppliedInputTypesMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ModerationCategoryAppliedInputTypesMultiError) AllErrors() []error { return m }

// ModerationCategoryAppliedInputTypesValidationError is the validation error
// returned by ModerationCategoryAppliedInputTypes.Validate if the designated
// constraints aren't met.
type ModerationCategoryAppliedInputTypesValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ModerationCategoryAppliedInputTypesValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ModerationCategoryAppliedInputTypesValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ModerationCategoryAppliedInputTypesValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ModerationCategoryAppliedInputTypesValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ModerationCategoryAppliedInputTypesValidationError) ErrorName() string {
	return "ModerationCategoryAppliedInputTypesValidationError"
}

// Error satisfies the builtin error interface
func (e ModerationCategoryAppliedInputTypesValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sModerationCategoryAppliedInputTypes.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ModerationCategoryAppliedInputTypesValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ModerationCategoryAppliedInputTypesValidationError{}

// Validate checks the field values on ModerationResult with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ModerationResult) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ModerationResult with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ModerationResultMultiError, or nil if none found.
func (m *ModerationResult) ValidateAll() error {
	return m.validate(true)
}

func (m *ModerationResult) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Flagged

	if all {
		switch v := interface{}(m.GetCategories()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ModerationResultValidationError{
					field:  "Categories",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ModerationResultValidationError{
					field:  "Categories",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCategories()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ModerationResultValidationError{
				field:  "Categories",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCategoryScores()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ModerationResultValidationError{
					field:  "CategoryScores",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ModerationResultValidationError{
					field:  "CategoryScores",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCategoryScores()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ModerationResultValidationError{
				field:  "CategoryScores",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCategoryAppliedInputTypes()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ModerationResultValidationError{
					field:  "CategoryAppliedInputTypes",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ModerationResultValidationError{
					field:  "CategoryAppliedInputTypes",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCategoryAppliedInputTypes()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ModerationResultValidationError{
				field:  "CategoryAppliedInputTypes",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ModerationResultMultiError(errors)
	}

	return nil
}

// ModerationResultMultiError is an error wrapping multiple validation errors
// returned by ModerationResult.ValidateAll() if the designated constraints
// aren't met.
type ModerationResultMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ModerationResultMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ModerationResultMultiError) AllErrors() []error { return m }

// ModerationResultValidationError is the validation error returned by
// ModerationResult.Validate if the designated constraints aren't met.
type ModerationResultValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ModerationResultValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ModerationResultValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ModerationResultValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ModerationResultValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ModerationResultValidationError) ErrorName() string { return "ModerationResultValidationError" }

// Error satisfies the builtin error interface
func (e ModerationResultValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sModerationResult.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ModerationResultValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ModerationResultValidationError{}

// Validate checks the field values on ModerationResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ModerationResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ModerationResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ModerationResponseMultiError, or nil if none found.
func (m *ModerationResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ModerationResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Model

	for idx, item := range m.GetResults() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ModerationResponseValidationError{
						field:  fmt.Sprintf("Results[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ModerationResponseValidationError{
						field:  fmt.Sprintf("Results[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ModerationResponseValidationError{
					field:  fmt.Sprintf("Results[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ModerationResponseMultiError(errors)
	}

	return nil
}

// ModerationResponseMultiError is an error wrapping multiple validation errors
// returned by ModerationResponse.ValidateAll() if the designated constraints
// aren't met.
type ModerationResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ModerationResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ModerationResponseMultiError) AllErrors() []error { return m }

// ModerationResponseValidationError is the validation error returned by
// ModerationResponse.Validate if the designated constraints aren't met.
type ModerationResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ModerationResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ModerationResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ModerationResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ModerationResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ModerationResponseValidationError) ErrorName() string {
	return "ModerationResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ModerationResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sModerationResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ModerationResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ModerationResponseValidationError{}
