// @generated by protoc-gen-es v2.9.0 with parameter "target=js,json_types=true,import_extension=js"
// @generated from file everstack/catalog/v1/catalog.proto (package everstack.catalog.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file everstack/catalog/v1/catalog.proto.
 */
export const file_everstack_catalog_v1_catalog = /*@__PURE__*/
  fileDesc("CiJldmVyc3RhY2svY2F0YWxvZy92MS9jYXRhbG9nLnByb3RvEhRldmVyc3RhY2suY2F0YWxvZy52MSIZChdHZXRDYXRhbG9nU3RhdHVzUmVxdWVzdCIrChNHZXRDaGFuZ2Vsb2dSZXF1ZXN0EhQKDGZyb21fdmVyc2lvbhgBIAEoCSInChNHZXROZXdNb2RlbHNSZXF1ZXN0EhAKCHByb3ZpZGVyGAEgASgJIiMKElRyaWdnZXJTeW5jUmVxdWVzdBINCgVmb3JjZRgBIAEoCCLbAQoNQ2F0YWxvZ1N0YXR1cxIXCg9jdXJyZW50X3ZlcnNpb24YASABKAkSFgoOcmVtb3RlX3ZlcnNpb24YAiABKAkSEgoKbGFzdF9jaGVjaxgDIAEoCRIUCgxzeW5jX2VuYWJsZWQYBCABKAgSEAoIc3luY191cmwYBSABKAkSGAoQbmV3X21vZGVsc19jb3VudBgGIAEoBRIbChNuZXdfcHJvdmlkZXJzX2NvdW50GAcgASgFEhEKCWxhc3Rfc3luYxgIIAEoCRITCgtoYXNfdXBkYXRlcxgJIAEoCCK7AQoOQ2hhbmdlbG9nRW50cnkSDwoHdmVyc2lvbhgBIAEoCRIMCgRkYXRlGAIgASgJEhMKC2Rlc2NyaXB0aW9uGAMgASgJEhIKCm5ld19tb2RlbHMYBCADKAkSFQoNbmV3X3Byb3ZpZGVycxgFIAMoCRIWCg51cGRhdGVkX21vZGVscxgGIAMoCRIZChFkZXByZWNhdGVkX21vZGVscxgHIAMoCRIXCg9wcmljaW5nX2NoYW5nZXMYCCADKAkiQgoJQ2hhbmdlbG9nEjUKB2VudHJpZXMYASADKAsyJC5ldmVyc3RhY2suY2F0YWxvZy52MS5DaGFuZ2Vsb2dFbnRyeSKxAQoITmV3TW9kZWwSEAoIcHJvdmlkZXIYASABKAkSDAoEbmFtZRgCIAEoCRIUCgxkaXNwbGF5X25hbWUYAyABKAkSEgoKbWF4X3Rva2VucxgEIAEoAxIZChFpbnB1dF9jb3N0X3Blcl8xaxgFIAEoARIaChJvdXRwdXRfY29zdF9wZXJfMWsYBiABKAESFAoMY2FwYWJpbGl0aWVzGAcgAygJEg4KBnN0YXR1cxgIIAEoCSJQCglOZXdNb2RlbHMSLgoGbW9kZWxzGAEgAygLMh4uZXZlcnN0YWNrLmNhdGFsb2cudjEuTmV3TW9kZWwSEwoLdG90YWxfY291bnQYAiABKAUidgoKU3luY1N0YXR1cxIPCgdzdWNjZXNzGAEgASgIEg8KB21lc3NhZ2UYAiABKAkSDwoHdmVyc2lvbhgDIAEoCRIYChBuZXdfbW9kZWxzX2NvdW50GAQgASgFEhsKE25ld19wcm92aWRlcnNfY291bnQYBSABKAVC5AEKGGNvbS5ldmVyc3RhY2suY2F0YWxvZy52MUIMQ2F0YWxvZ1Byb3RvUAFaSGdpdGh1Yi5jb20vZXZlcnN0YWNrbGFicy9ldmVyc3RhY2svcGtnL2dycGMvZXZlcnN0YWNrL2NhdGFsb2cvdjE7Y2F0YWxvZ6ICA0VDWKoCFEV2ZXJzdGFjay5DYXRhbG9nLlYxygIURXZlcnN0YWNrXENhdGFsb2dcVjHiAiBFdmVyc3RhY2tcQ2F0YWxvZ1xWMVxHUEJNZXRhZGF0YeoCFkV2ZXJzdGFjazo6Q2F0YWxvZzo6VjFiBnByb3RvMw");

/**
 * Describes the message everstack.catalog.v1.GetCatalogStatusRequest.
 * Use `create(GetCatalogStatusRequestSchema)` to create a new message.
 */
export const GetCatalogStatusRequestSchema = /*@__PURE__*/
  messageDesc(file_everstack_catalog_v1_catalog, 0);

/**
 * Describes the message everstack.catalog.v1.GetChangelogRequest.
 * Use `create(GetChangelogRequestSchema)` to create a new message.
 */
export const GetChangelogRequestSchema = /*@__PURE__*/
  messageDesc(file_everstack_catalog_v1_catalog, 1);

/**
 * Describes the message everstack.catalog.v1.GetNewModelsRequest.
 * Use `create(GetNewModelsRequestSchema)` to create a new message.
 */
export const GetNewModelsRequestSchema = /*@__PURE__*/
  messageDesc(file_everstack_catalog_v1_catalog, 2);

/**
 * Describes the message everstack.catalog.v1.TriggerSyncRequest.
 * Use `create(TriggerSyncRequestSchema)` to create a new message.
 */
export const TriggerSyncRequestSchema = /*@__PURE__*/
  messageDesc(file_everstack_catalog_v1_catalog, 3);

/**
 * Describes the message everstack.catalog.v1.CatalogStatus.
 * Use `create(CatalogStatusSchema)` to create a new message.
 */
export const CatalogStatusSchema = /*@__PURE__*/
  messageDesc(file_everstack_catalog_v1_catalog, 4);

/**
 * Describes the message everstack.catalog.v1.ChangelogEntry.
 * Use `create(ChangelogEntrySchema)` to create a new message.
 */
export const ChangelogEntrySchema = /*@__PURE__*/
  messageDesc(file_everstack_catalog_v1_catalog, 5);

/**
 * Describes the message everstack.catalog.v1.Changelog.
 * Use `create(ChangelogSchema)` to create a new message.
 */
export const ChangelogSchema = /*@__PURE__*/
  messageDesc(file_everstack_catalog_v1_catalog, 6);

/**
 * Describes the message everstack.catalog.v1.NewModel.
 * Use `create(NewModelSchema)` to create a new message.
 */
export const NewModelSchema = /*@__PURE__*/
  messageDesc(file_everstack_catalog_v1_catalog, 7);

/**
 * Describes the message everstack.catalog.v1.NewModels.
 * Use `create(NewModelsSchema)` to create a new message.
 */
export const NewModelsSchema = /*@__PURE__*/
  messageDesc(file_everstack_catalog_v1_catalog, 8);

/**
 * Describes the message everstack.catalog.v1.SyncStatus.
 * Use `create(SyncStatusSchema)` to create a new message.
 */
export const SyncStatusSchema = /*@__PURE__*/
  messageDesc(file_everstack_catalog_v1_catalog, 9);

